const Map<String, String> appLanguageJa = {
  'app_title': 'Doujin Audio',
  'startup_initializing': 'Doujin Audio を起動しています…',
  'startup_error_title': 'Doujin Audio を起動できませんでした',
  'startup_error_message': 'ローカルデータは失われません。再試行するか、診断レポートを出力してください。',
  'permission_group_playback': '再生の基本',
  'permission_group_reliability': 'タイマーと信頼性',
  'permission_group_advanced': '高度な機能',
  'onboarding_title': 'Doujin Audio',
  'onboarding_subtitle': 'ローカル優先の ASMR・音声プレーヤーです。',
  'onboarding_local': 'ライブラリと再生状態はこの端末に保存されます。',
  'onboarding_online_optional': 'ASMR.ONE などのオンライン機能は任意です。',
  'onboarding_permissions': '権限は関連機能を使用するときだけ要求します。',
  'onboarding_start': '始める',
  'privacy_summary_action': 'プライバシー概要を見る',
  'privacy_summary_title': 'プライバシー概要',
  'privacy_summary_local_title': 'ローカル保存が基本',
  'privacy_summary_local_body': 'ライブラリ、設定、再生状態はこの端末に保存されます。',
  'privacy_summary_network_title': '任意のオンライン機能',
  'privacy_summary_network_body': '通信はASMR.ONE、メタデータ、更新などでのみ使用します。',
  'privacy_summary_diagnostics_title': '診断情報はユーザーが管理',
  'privacy_summary_diagnostics_body': '選択して書き出した場合のみ、匿名化した診断情報を作成します。',
  'nav_library': '音声ライブラリ',
  'open_library': 'ライブラリを開く',
  'open_playback_details': '再生詳細を開く',
  'retry_playback': '再生を再試行',
  'nav_sessions': 'プレイリスト',
  'nav_settings': '設定',
  'timer': 'タイマー',
  'done': '完了',
  'close': '閉じる',
  'fullscreen': '全画面',
  'exit_fullscreen': '全画面表示を終了',
  'brightness': '明るさ',
  'seek_backward_five_seconds': '5秒戻る',
  'seek_forward_five_seconds': '5秒進む',
  'temporary_double_speed': '一時的に 2.0倍速',
  'open_timer_settings': 'タイマー設定を開く',
  'timer_play_plus': '再生 + {time}',
  'asmr_player': 'NL Audio',
  'music_library': '音声ライブラリ',
  'playback_sessions': 'プレイリスト',
  'pin_to_top': '先頭に固定',
  'unpin_from_top': '固定を解除',
  'pinned_to_top': '固定中',
  'settings': '設定',
  'asmr_header_stats': '現在 {count} 作品を収録',
  'library_header_stats': '{works} 作品  {sessions} セッション',
  'playlist_header_stats': '{sessions} セッション  {playing} 再生中',
  'video_to_audio': '動画を音声に変換',
  'import_audio': '音声を追加',
  'import_folder': 'フォルダを追加',
  'import_file': 'ファイルを追加',
  'import_library': 'ライブラリを追加',
  'refresh_watched_folder': '監視フォルダを更新',
  'more_actions': 'その他の操作',
  'sort_by': '並び順',
  'sort_by_title': '並び順',
  'sort_description': '説明',
  'sort_name': '名前',
  'sort_voice_actor': '声優',
  'sort_duration': '再生時間',
  'sort_release_date': '発売日時',
  'sort_added_date': '追加日時',
  'sort_playback_time': '再生日時',
  'sort_ascending': '昇順',
  'sort_descending': '降順',
  'sort_group_by_library': 'ライブラリ分類',
  'batch_metadata': 'データを一括補完',
  'batch_metadata_hint':
      'ASMR.ONE の作品情報を優先して取得し、失敗した場合は DLsite を使用します。現在の作品を確認すると、次の作品へ進みます。',
  'batch_metadata_no_metadata': 'すべてのデータが不足している作品',
  'batch_metadata_any_missing': '不足データがある作品',
  'batch_metadata_has_rj_code': 'RJ番号が入力済みの作品',
  'batch_metadata_specific': '作品を指定',
  'batch_metadata_picker_search': 'RJ番号やタイトルを検索',
  'batch_metadata_picker_done': '完了 ({count})',
  'batch_metadata_all': 'すべてのデータ',
  'batch_metadata_start': '補完を開始',
  'batch_metadata_status_searching': '検索中',
  'batch_metadata_status_found': '取得済み（未確認）',
  'batch_metadata_status_confirmed': '取得済み（確認済み）',
  'batch_metadata_status_not_found': '見つかりません',
  'batch_metadata_status_failed': '検索に失敗しました',
  'batch_metadata_status_excluded': '除外',
  'batch_metadata_action_exclude': '除外',
  'batch_metadata_action_restore': '復元',
  'batch_metadata_progress': '{current} / {total}',
  'batch_metadata_load_failed': 'ローカルライブラリを読み込めませんでした。もう一度お試しください。',
  'batch_metadata_completion_title': '一括補完が完了しました',
  'batch_metadata_completion_saved': '{count} 件の作品データを保存しました',
  'batch_metadata_completion_skipped': '{count} 件の作品データをスキップしました',
  'batch_metadata_completion_failed': '{count} 件の作品データに失敗しました',
  'library_manage_empty': '追加済みのライブラリはありません。',
  'skip': 'スキップ',
  'search': '検索',
  'search_audio_placeholder': '音声を検索…',
  'scanning_title': 'スキャン中',
  'loading_dot': '読み込み中...',
  'playback_loading': '読み込み中',
  'playback_state_playing': '再生中',
  'playback_state_paused': '一時停止中',
  'playback_failed_retry': '再生に失敗しました。再生ボタンで再試行',
  'playback_network_failed_retry': 'ネットワーク接続に失敗しました。再生ボタンで再試行',
  'asmr_playback_load_failed_retry': '読み込みに失敗しました。タップして再試行',
  'asmr_playback_network_failed_retry': 'ネットワーク接続に失敗しました。タップして再試行',
  'asmr_network_failed_retry': 'ネットワーク接続に失敗しました。下に引っ張って再試行してください。',
  'asmr_authentication_failed_retry': 'ログインの有効期限が切れました。再度ログインしてください。',
  'scan_cancel': 'スキャンをキャンセル',
  'scan_cancelled': 'スキャンをキャンセルしました。',
  'scan_stage_preparing': 'フォルダーを読み込み中...',
  'scan_stage_enumerating': '音声ファイルを検索中...',
  'scan_stage_merging': '曲情報を読み込み中...',
  'scan_stage_saving': 'ライブラリを保存中...',
  'scan_stage_covers': 'カバーを読み込み中...',
  'scan_processed': '{processed} 件を処理済み',
  'scan_processed_total': '{processed} / {total} 件を処理済み',
  'scan_current_folder': '現在のフォルダ',
  'scan_found': '発見',
  'scan_duplicate': '重複',
  'scan_failure': '失敗',
  'audio_count': '{count} 曲',
  'folder_count': '{count} フォルダ',
  'no_audio_files': '音声ファイルがありません',
  'no_audio_found': '音声ファイルが見つかりませんでした。',
  'no_search_results': '一致する検索結果がありません',
  'search_try_another_term': '別のキーワードを試すか、検索をクリアしてください。',
  'search_match_count': '{match} / {total} 曲一致',
  'import_audio_hint': '下のボタンから音声を追加できます。フォルダ/ファイル両方に対応します。',
  'need_storage_permission_scan_folder': 'フォルダをスキャンするにはストレージ権限が必要です。',
  'need_storage_permission_import_audio': '音声を追加するにはストレージ権限が必要です。',
  'import_audio_failed': '音声を追加できませんでした。再試行してください。',
  'import_failed_next_step': '選択したファイルまたはフォルダにまだアクセスできるか確認してから、もう一度お試しください。',
  'scan_failed_next_step': 'ストレージ権限と元のフォルダがまだ存在するか確認してから、もう一度お試しください。',
  'detail_backup_import_failed':
      '{count} 件の詳細バックアップを同期できませんでした。doujin-audio.json を確認して再試行してください。',
  'refresh_done_added': '更新完了：{count} 曲を追加しました。',
  'refresh_done_no_new': '新しい音声は見つかりませんでした。',
  'asmr_refresh_done_updated': 'カテゴリ内容を更新しました。',
  'asmr_online_playback': 'ASMR.ONE オンライン再生',
  'asmr_online_optional_notice': 'ASMR.ONE は任意のオンライン機能で、使用中のみネットワークに接続します。',
  'asmr_refresh_no_updates': '新しい更新はありません。',
  'asmr_refresh_failed': '同期に失敗しました。下に引っ張って再試行してください。',
  'asmr_favorite_added': 'お気に入りに追加しました。',
  'asmr_favorite_removed': 'お気に入りを解除しました。',
  'asmr_category_sales': '販売数',
  'asmr_category_rating': '評価',
  'asmr_category_reviews': 'レビュー数',
  'asmr_category_release': '発売',
  'asmr_category_collected': '収録日時',
  'asmr_category_recommendation': 'おすすめ',
  'asmr_category_favorites': 'お気に入り',
  'asmr_category_history': '履歴',
  'asmr_account_menu': 'アカウント',
  'asmr_account_title': 'ASMR.ONE アカウント',
  'asmr_account_restoring': 'アカウント情報を復元しています…',
  'asmr_login_title': 'ログイン',
  'asmr_login_account': 'アカウント',
  'asmr_login_password': 'パスワード',
  'asmr_login_action': 'ログイン',
  'asmr_logout_action': 'ログアウト',
  'asmr_logged_in_as': 'ログイン中：{name}',
  'asmr_login_success': 'ログインしました。',
  'asmr_logout_success': 'ログアウトしました。',
  'asmr_login_failed': 'ログインに失敗しました。アカウントとパスワードを確認してください。',
  'asmr_token_expired': 'ログインの有効期限が切れました。再ログインしてください。',
  'asmr_account_sync_now': '今すぐ同期',
  'asmr_account_syncing': 'アカウントデータを同期中...',
  'asmr_account_sync_done': 'アカウントデータを同期しました。',
  'asmr_account_sync_failed': 'アカウント同期に失敗しました。あとでもう一度お試しください。',
  'asmr_account_not_synced': 'まだ同期されていません。',
  'asmr_account_last_sync': '前回の同期：{time}',
  'asmr_account_pending_count': '同期待ちの変更が {count} 件あります',
  'asmr_categories_title': '分類',
  'follow_interface_language': 'アプリに合わせる',
  'asmr_page_language': 'ASMR.ONE の表示言語',
  'asmr_language_zh': '中国語',
  'asmr_language_ja': '日本語',
  'asmr_language_en': '英語',
  'asmr_search_hint': '作品を検索...',
  'asmr_empty_category': 'このカテゴリにはまだ内容がありません。',
  'asmr_load_more_hint': 'さらに読み込むには上へスワイプ',
  'asmr_add_to_playlist': 'プレイリストに追加',
  'add_to_playlist': 'プレイリストに追加',
  'asmr_added_to_playlist': 'プレイリストに追加しました：{title}',
  'asmr_detail_action': '詳細情報',
  'asmr_detail_tooltip': '作品の詳細情報を表示',
  'asmr_favorite_action': 'お気に入り',
  'asmr_unfavorite_action': 'お気に入り解除',
  'asmr_add_favorite_tooltip': 'お気に入りに追加',
  'asmr_download_action': 'ダウンロード',
  'asmr_download_work_tooltip': '作品をダウンロード',
  'asmr_empty_track_tree': 'この作品には展開できる音声ツリーがありません。',
  'asmr_circle_label': '団体',
  'asmr_tags_label': 'タグ',
  'asmr_detail_title': '詳細情報',
  'asmr_detail_readonly_hint': '読み取り専用モードです。編集やドラッグ並べ替えはできません。',
  'asmr_detail_load_failed': '作品情報の読み込みに失敗しました。しばらくしてから再試行してください。',
  'asmr_detail_basic_info': '基本情報',
  'asmr_detail_other': 'その他の情報',
  'asmr_detail_statistics': '統計情報',
  'asmr_detail_release_date': '発売日',
  'asmr_detail_duration': '再生時間',
  'asmr_detail_sales': '販売数',
  'asmr_detail_rating': '評価',
  'asmr_detail_unrated': '未評価',
  'asmr_detail_reviews': 'レビュー数',
  'asmr_detail_age_rating': '年齢区分',
  'asmr_detail_language_editions': '言語版',
  'asmr_detail_description': '説明',
  'asmr_unknown_circle': '不明なサークル',
  'asmr_missing_rj': 'RJ番号なし',
  'asmr_has_subtitle': '字幕あり',
  'asmr_unknown': '不明',
  'asmr_download_title': 'ダウンロード',
  'asmr_download_choose_path': '保存先を選択',
  'asmr_download_change_path': '保存先を変更',
  'asmr_download_path_missing': '保存済みのダウンロード先が見つかりません。保存先を選び直してください。',
  'asmr_download_conflict_title': '同名項目の処理',
  'asmr_download_conflict_message': '保存先に同名のファイルやフォルダがある場合、どう処理しますか？',
  'asmr_download_conflict_skip': 'スキップ',
  'asmr_download_conflict_overwrite': '上書き',
  'asmr_download_task_running': '現在実行中のダウンロードタスクがあります',
  'asmr_download_select_required': 'ダウンロードするファイルまたはフォルダを先に選択してください',
  'asmr_download_completed_with_failures': 'ダウンロードは完了しましたが、一部のファイルに失敗しました',
  'asmr_download_failed': 'ダウンロードに失敗しました：{error}',
  'asmr_download_failed_title': 'ダウンロードに失敗しました',
  'asmr_download_failed_next_step': '保存先フォルダとネットワーク接続を確認してから、もう一度お試しください。',
  'asmr_download_starting': 'ダウンロード中',
  'asmr_download_confirm': 'ダウンロードを開始',
  'asmr_download_added_to_list': 'ダウンロードリストに追加しました',
  'asmr_download_task_title': 'ダウンロードタスク',
  'asmr_download_task_not_found': 'ダウンロードタスクが見つかりません',
  'asmr_download_details_title': 'ダウンロード詳細',
  'asmr_download_no_files_selected': 'ファイルが選択されていません',
  'asmr_download_remove_task': 'ダウンロードタスクを削除',
  'asmr_download_remove_entry': 'タスク項目のみ削除',
  'asmr_download_remove_and_delete': 'ダウンロード済みの内容も削除',
  'asmr_download_no_tasks': 'ダウンロードタスクはありません',
  'asmr_download_waiting': '待機中',
  'asmr_download_status': '状態',
  'asmr_download_destination': '保存先',
  'asmr_download_progress': '進捗',
  'asmr_download_skipped': 'スキップ済み',
  'asmr_download_failed_count': '失敗',
  'asmr_download_downloaded': 'ダウンロード済み',
  'asmr_download_total_size': '合計サイズ',
  'asmr_download_task_removed': 'タスク項目を削除しました',
  'asmr_download_task_removed_and_deleted': 'タスクとダウンロード済みの内容を削除しました',
  'asmr_download_summary_selected': '{count} 個のファイルを選択中、合計 {size}。',
  'asmr_download_empty_folder': '空のフォルダ',
  'asmr_download_status_preparing': '準備中',
  'asmr_download_status_downloading': 'ダウンロード中',
  'asmr_download_status_retrying': '再試行中（{attempt}/{max}）',
  'asmr_download_status_paused': '一時停止',
  'asmr_download_status_completed': '完了',
  'asmr_download_status_failed': '失敗',
  'asmr_download_status_idle': '待機中',
  'refresh': '更新',
  'downloads': 'ダウンロード一覧',
  'choose_music_folder': '音楽フォルダを選択',
  'import_done_added': '追加完了：{count} 曲を追加しました。',
  'choose_audio_files': '音声ファイルを選択',
  'library_folder_exists': '重複したフォルダがすでに存在します。',
  'library_exists': '重複したライブラリがすでに存在します。',
  'library_file_exists': '重複したファイルがすでに存在します。',
  'imported_files': '追加済みファイル',
  'manually_selected_files': '手動選択ファイル',
  'file_added': 'ファイル追加',
  'library_category_all': 'すべて',
  'library_category_tags': 'タグ',
  'library_category_voice_actors': '声優',
  'library_category_circles': 'サークル',
  'library_category_no_tags': 'タグ情報がありません',
  'library_category_no_voice_actors': '声優情報がありません',
  'library_category_no_circles': 'サークル情報がありません',
  'library_category_no_matches': '一致する音声がありません',
  'copied_to_clipboard': 'コピーしました：{value}',
  'remove_folder': 'フォルダを削除',
  'remove_folder_confirm': 'このフォルダと配下の音声をライブラリから削除しますか？\n\n{name}',
  'cancel': 'キャンセル',
  'remove': '削除',
  'removed_prefix': '削除済み：{name}',
  'session_created': 'セッション作成：{name}',
  'items_count': '{count} 項目',
  'play_first': '先頭を再生',
  'remove_audio_folder': 'フォルダを削除',
  'play': '再生',
  'create_another_session': 'もう1つ作成',
  'remove_audio': '音声を削除',
  'audio_detail': '詳細情報',
  'audio_detail_title': '詳細情報',
  'audio_detail_library_root': 'ライブラリのルートフォルダ',
  'audio_detail_single_file': '単独追加音声',
  'audio_detail_cover_image': 'カバー画像',
  'audio_detail_folder_name': 'フォルダ名',
  'audio_detail_file_name': 'ファイル名',
  'audio_detail_rj_code': 'RJ番号',
  'audio_detail_work_title': '作品タイトル',
  'audio_detail_circle_name': 'サークル名',
  'audio_detail_voice_actors': '声優名',
  'audio_detail_tags': 'タグ',
  'audio_detail_release_date': '発売日',
  'audio_detail_sales_count': '販売数',
  'audio_detail_rating': '評価',
  'audio_detail_empty': '未入力',
  'audio_detail_edit_title': '{name}を編集',
  'audio_detail_multi_hint': '複数項目は中国語の読点「，」で区切ってください',
  'audio_detail_backup_failed': 'データベースに保存しましたが、ローカルバックアップに失敗しました。',
  'audio_detail_cover_portability_skipped':
      'カバーが 8 MiB を超えているため、端末上のパスのみ保持し、ポータブルバックアップには保存しませんでした。',
  'audio_detail_restored_from_backup': 'ローカルバックアップから復元しました。',
  'audio_detail_rj_format_hint': 'RJ番号は RJ + 数字の形式を推奨します。',
  'audio_detail_save_failed': '保存に失敗しました。もう一度お試しください。',
  'audio_detail_load_failed': '読み込みに失敗しました。もう一度お試しください。',
  'audio_detail_duration_calculation_failed': '再生時間を計算できませんでした。もう一度お試しください。',
  'audio_detail_fetch_info': '情報を取得',
  'audio_detail_fetch_scope_title': '取得範囲を選択',
  'audio_detail_fetch_scope_hint':
      'ASMR.ONE を優先して作品情報を取得し、失敗した場合は DLsite を使用します。書き込む範囲を選択してください。',
  'audio_detail_fetch_scope_all_hint': '取得した情報で現在の詳細情報を上書きします。',
  'audio_detail_fetch_scope_missing_hint': '空欄の詳細情報のみ入力し、既存の内容は保持します。',
  'metadata_scope_missing': '不足データ',
  'audio_detail_fetch_missing_query': 'RJ番号、フォルダ/ファイル名、または作品タイトルを入力してください。',
  'audio_detail_cover_swipe_hint': '左右にスワイプして切り替え',
  'audio_detail_set_cover': 'カバーに設定',
  'audio_detail_current_cover': '現在のカバー',
  'audio_detail_rename_file': 'ファイル名を変更',
  'audio_detail_rename_failed': '名前の変更に失敗しました。ファイルの存在や使用状態を確認してください。',
  'dlsite_review_title': '作品データを確認',
  'dlsite_save_cover': 'カバーをフォルダに保存',
  'dlsite_fetch_failed':
      '作品データを取得できませんでした。RJ番号、フォルダ/ファイル名、作品タイトル、またはネットワークを確認してください。',
  'dlsite_cover_save_failed': '情報は保存しましたが、カバーの保存に失敗しました。',
  'confirm': '確認',
  'retry': '再試行',
  'undo': '元に戻す',
  'items_removed_count': '{count}件を削除しました',
  'removal_failed': '一部の項目を削除できませんでした。もう一度お試しください。',
  'previous': '前へ',
  'next': '次へ',
  'clear_all_sessions': '全セッションをクリア',
  'stop_remove_all_sessions': '実行中の再生セッションをすべて停止して削除しますか？',
  'clear': 'クリア',
  'all_sessions_cleared': '全セッションをクリアしました。',
  'audio_removed': '音声を削除しました。',
  'audio_excluded': 'ライブラリから音声を除外しました。',
  'folder_audio_removed': 'フォルダー内の音声を削除しました。',
  'folder_removed': 'フォルダを削除しました。',
  'folder_excluded': 'ライブラリからフォルダを除外しました。',
  'pause_all_sessions': '全セッションを一時停止',
  'all_paused': '全セッションを一時停止しました。',
  'no_active_sessions': 'アクティブなセッションはありません',
  'go_library_hint': '先にライブラリで音声を再生してから、並行セッションを作成してください。',
  'single_loop': '1曲リピート',
  'pause_after_playback': 'リスト1周後に停止',
  'loop_mode_title': '再生モード',
  'sequential_playback': '順番再生',
  'loop_playback': '順番再生',
  'shuffle_playback': 'シャッフル再生',
  'cross_folder': 'フォルダ横断',
  'current_folder': '現在のフォルダ',
  'random_order': 'ランダム',
  'sequential_order': '順番',
  'no_other_audio_in_folder': 'このフォルダには切り替え可能な他の音声がありません。',
  'switch_audio': '音声を切替',
  'channel_swap': '左右チャンネル入れ替え',
  'channel_swap_desc': '左右の音声を入れ替えます。',
  'skip_silence': '無音スキップ',
  'skip_silence_desc': '無音部分を短縮します。',
  'noise_reduction': 'ノイズ低減',
  'noise_reduction_desc': '鋭いノイズを軽減します。',
  'volume_normalization': '音量ノーマライズ',
  'volume_normalization_desc': '突発的な音量を抑え均一化します。',
  'audio_features': '機能',
  'equalizer': 'イコライザー',
  'time_segments': '時間区間',
  'equalizer_supported': 'この端末の対応バンドで調整します。',
  'equalizer_enable_hint': 'オンにすると端末の対応バンドを読み込みます。',
  'equalizer_unavailable': 'EQ バンドをまだ取得できません。オンにして少し待ってください。',
  'eq_preset': 'プリセット',
  'eq_reset': 'リセット',
  'eq_save_preset': 'プリセット保存',
  'eq_delete_preset': 'プリセット削除',
  'eq_preset_name': 'プリセット名',
  'mute': 'ミュート',
  'unmute': 'ミュート解除',
  'eq_preset_flat': 'フラット',
  'eq_preset_asmr_immersive': 'ASMR没入',
  'eq_preset_voice_clear': '声を明瞭に',
  'eq_preset_ear_massage': '耳かき・マッサージ',
  'eq_preset_night_soft': '夜間ソフト',
  'eq_preset_bass_boost': '低音強調',
  'previous_track': '前の曲',
  'pause': '一時停止',
  'resume': '再開',
  'next_track': '次へ',
  'collapse': '折りたたむ',
  'expand': '展開',
  'end_session': 'セッション終了',
  'random_play': 'ランダム再生',
  'sequential_play': '順番再生',
  'cross_folder_play': 'フォルダ横断再生',
  'current_folder_only': '現在フォルダのみ',
  'dark_mode': '表示モード',
  'cover_image_resolution': 'カバー画質',
  'cover_image_resolution_300': '300px',
  'cover_image_resolution_600': '600px',
  'cover_image_resolution_900': '900px',
  'cover_image_resolution_1200': '1200px',
  'cover_image_resolution_original': 'オリジナル',
  'cover_image_display_mode': 'カバー画像の表示方法',
  'cover_image_display_mode_fill': '塗りつぶし',
  'cover_image_display_mode_stretch': '引き伸ばし',
  'cover_image_display_mode_tile': 'ぼかし背景で全体表示',
  'prefer_embedded_audio_cover': '音声の埋め込みカバーを優先',
  'theme_system': 'システム',
  'theme_light': 'ライト',
  'theme_dark': 'ダーク',
  'black_theme': '純黒テーマ',
  'differentiate_asmr_theme': 'ASMR.ONE 専用カラー',
  'app_theme_color': 'アプリのテーマカラー',
  'asmr_theme_color': 'ASMR.ONE のテーマカラー',
  'theme_color_coral': 'コーラル',
  'theme_color_rose': 'ローズ',
  'theme_color_pink': 'ピンク',
  'theme_color_lavender': 'ラベンダー',
  'theme_color_periwinkle': 'ペリウィンクル',
  'theme_color_blue': 'ブルー',
  'theme_color_sky': 'スカイブルー',
  'theme_color_cyan': 'シアン',
  'theme_color_mint': 'ミント',
  'theme_color_green': 'グリーン',
  'theme_color_light_green': 'ライトグリーン',
  'theme_color_lime': 'ライム',
  'theme_color_amber': 'アンバー',
  'theme_color_orange': 'オレンジ',
  'theme_color_peach': 'ピーチ',
  'theme_color_gray': 'グレー',
  'playback_detail_subtitle_style': '再生詳細の字幕スタイル',
  'playback_detail_subtitle_style_compact': 'シンプル字幕',
  'playback_detail_subtitle_style_timeline': 'タイムライン字幕',
  'seek_to_subtitle': 'この字幕へ移動',
  'blur_player_background': '再生画面の背景ぼかし',
  'ui_blur_effect': '画面のガラス効果',
  'multi_thread_playback': '複数音声を同時再生',
  'allow_video_playback': '動画の再生を許可',
  'notification_bar': '再生通知コントロール',
  'show_playback_card': '再生カードを表示',
  'section_detail_info': '詳細情報',
  'card_info_display': 'カード表示内容',
  'card_info_display_subtitle': '{count} / {max} 項目を選択中',
  'card_info_none': '表示しない',
  'card_info_release_date': '発売',
  'card_info_sales_count': '販売数',
  'card_info_rating': '評価',
  'card_info_duration': '時間',
  'auto_play_added_sessions': '追加後に再生',
  'audio_device_disconnect_behavior': 'ヘッドホン切断時',
  'audio_device_disconnect_pause': '一時停止',
  'audio_device_disconnect_continuePlayback': '続行',
  'audio_focus_strategy': 'オーディオフォーカス',
  'audio_focus_strategy_standard': '標準',
  'audio_focus_strategy_mixWithOthers': '重ねて再生',
  'transient_audio_focus_loss_behavior': '他の音声で中断した時',
  'transient_audio_focus_loss_duck': '音量を下げる',
  'transient_audio_focus_loss_pause': '一時停止',
  'interruption_resume_behavior': '通話終了後',
  'interruption_resume_stayPaused': '一時停止を維持',
  'interruption_resume_resume': '自動再開',
  'asmr_playback_cache': 'ASMR.ONE 音声をキャッシュ',
  'record_playback_progress': '再生位置を記憶',
  'section_language': '言語',
  'section_language_subtitle': '表示とコンテンツの言語',
  'section_common': '一般',
  'section_common_subtitle': '起動、動作、システム設定',
  'settings_group_startup_behavior': '起動設定',
  'settings_group_general_behavior': '一般動作',
  'settings_group_page_display': 'ページ表示',
  'show_local_library': '音楽ライブラリ',
  'show_asmr_one': 'ASMR.ONE',
  'settings_group_theme_layout': 'テーマとレイアウト',
  'settings_group_cover_background': 'カバーと背景',
  'settings_group_playback_detail': '再生詳細',
  'settings_group_playback_behavior': '再生動作',
  'settings_group_audio_recovery': '音声と復帰',
  'settings_group_download': 'ダウンロード',
  'settings_group_download_files': 'ファイルと命名',
  'settings_group_data': 'データとサポート',
  'settings_group_cache': 'キャッシュ',
  'settings_group_permissions': '権限とバックグラウンド',
  'settings_group_updates': '更新',
  'section_appearance': '外観',
  'section_appearance_subtitle': 'テーマ、レイアウト、字幕の外観',
  'section_playback': '再生',
  'section_playback_subtitle': '再生操作、音声、復帰',
  'section_asmr_download': 'ASMR.ONE ダウンロード',
  'section_asmr_download_subtitle': 'ダウンロードとファイル名',
  'asmr_download_path_setting': 'ダウンロード先',
  'asmr_download_path_not_set': '未設定',
  'asmr_download_conflict_setting': '既存ファイルの処理',
  'asmr_download_retry_count': '自動再試行回数',
  'asmr_download_thread_count': 'スレッド数',
  'asmr_download_save_metadata_setting': '作品情報を保存',
  'asmr_download_save_cover': 'カバー画像を保存',
  'asmr_download_folder_name_setting': 'フォルダー名',
  'asmr_download_folder_name_hint':
      '使用する項目を選択し、選択済みの項目をドラッグして並べ替えます。1項目以上必要です。',
  'asmr_download_folder_field_rj_code': 'RJ番号',
  'asmr_download_folder_field_voice_actors': '声優名',
  'asmr_download_folder_field_circle_name': 'サークル',
  'asmr_download_folder_field_work_title': '作品名',
  'section_data_storage': 'データとストレージ',
  'section_data_storage_subtitle': 'キャッシュとデータ管理',
  'section_updates_permissions': '更新と権限',
  'section_updates_permissions_subtitle': '権限、更新、バックグラウンド動作',
  'permission_state_authorized': '許可済み',
  'permission_state_unauthorized': '未許可',
  'permission_state_restricted': '制限あり',
  'permission_state_recommended': '推奨',
  'permission_enabled': '有効',
  'permission_not_enabled': '無効',
  'system_settings_open_failed': 'システム設定を開けませんでした。アプリ設定から手動で変更してください。',
  'permission_notification_description': 'バックグラウンド再生状態とメディア操作を表示します。',
  'permission_background_description': '画面オフ時に一部端末が再生を制限する可能性を減らします。',
  'permission_manage_files_description':
      'ファイルシステムを直接走査する高度な曲庫スキャンでのみ必要です。通常はシステムのフォルダ選択を推奨します。',
  'permission_overlay_description': '他のアプリ上にグローバル字幕を表示する場合のみ必要です。',
  'permission_update_install_description':
      'ユーザーが明示的にダウンロードした GitHub Release 更新のインストールにのみ使用します。',
  'storage_usage_title': 'ストレージ容量',
  'storage_usage_total': '端末の総容量',
  'storage_usage_audio_library': 'ローカル音声ライブラリ',
  'storage_usage_app_cache': 'アプリキャッシュ',
  'storage_usage_other': 'その他の使用容量',
  'storage_usage_available': '空き容量',
  'storage_usage_unavailable': 'ストレージ情報を一時的に読み取れません。',
  'storage_usage_retry': 'ストレージ情報を再読み込み',
  'operation_completed': '完了',
  'operation_failed': '操作に失敗しました',
  'export_diagnostics': '診断レポートを出力',
  'export_backup': 'バックアップを書き出す',
  'export_backup_subtitle': 'アプリデータ、再生履歴、ASMR.ONE のログイン情報を保存します。',
  'restore_backup': 'バックアップを復元',
  'restore_backup_subtitle': '現在のデータを完全に置き換え、次回起動時に適用します。',
  'backup_sensitive_warning':
      '暗号化されないバックアップに ASMR.ONE のアカウント名、パスワード、ログイントークンが含まれます。ファイルを入手した人がログインできる可能性があります。続行しますか？',
  'restore_backup_warning':
      '復元すると現在のアプリデータが完全に置き換わり、再生が停止します。音声ファイルとフォルダー権限は復元されません。完了後にアプリを閉じて再起動してください。',
  'select_backup': 'バックアップを選択',
  'backup_exported': 'バックアップの出力先：{path}',
  'backup_ready_to_restore': 'バックアップの準備が完了しました',
  'backup_restart_required': 'バックアップの検証が完了しました。次回起動時に復元されます。アプリを閉じて再起動してください。',
  'backup_restore_succeeded': 'バックアップを復元し、アプリデータと ASMR.ONE アカウントを更新しました。',
  'backup_restore_failed_rolled_back': 'バックアップの復元に失敗したため、以前のデータに安全に戻しました。',
  'unexpected_error_title': 'Doujin Audio で予期しないエラーが発生しました',
  'unexpected_error_message':
      'ローカルデータは保持されています。診断レポートを出力してから、アプリを閉じて再起動してください。',
  'close_and_restart': '閉じて再起動',
  'export_diagnostics_subtitle': '匿名化したログなどの診断情報を出力します。',
  'diagnostics_exported': '診断レポートの出力先：{path}',
  'operation_failed_retry': '操作に失敗しました。もう一度お試しください。',
  'operation_failed_diagnostics_hint': 'もう一度お試しください。問題が続く場合は診断レポートを出力してください。',
  'section_danger_zone': 'その他',
  'allow_background_run': 'バックグラウンド実行を許可',
  'allow_background_run_subtitle': 'バックグラウンド制限を防ぎます。',
  'allow_background_run_ready': 'このアプリのバックグラウンド実行は許可されています。画面オフ再生がより安定します。',
  'allow_background_run_checking': 'バックグラウンド実行の状態を確認しています...',
  'allow_background_run_open_failed': 'システム設定を開けませんでした。アプリ設定から手動で変更してください。',
  'notification_permission_status': '通知権限の状態',
  'notification_permission_ready': '通知権限は有効です。バックグラウンド操作を表示でき、画面オフ再生がより安定します。',
  'notification_permission_missing':
      '通知権限が無効です。システムがバックグラウンド再生通知や操作表示を制限する場合があります。',
  'notification_permission_checking': '通知権限を確認しています...',
  'notification_settings_open_failed': '通知設定を開けませんでした。システム設定から手動で変更してください。',
  'open_notification_settings': '通知設定を開く',
  'exact_alarm_permission_ready': '正確なアラームは利用可能です。長時間バックグラウンド後の自動再開がより安定します。',
  'exact_alarm_permission_missing':
      '正確なアラームが無効です。長時間バックグラウンド後の自動再開が不安定になる場合があります。',
  'clear_app_cache': 'アプリキャッシュを削除',
  'clear_app_cache_confirm':
      'このアプリが作成したキャッシュを削除します。ライブラリの元ファイルは削除されません。続行しますか？',
  'app_cache_cleaned': '{size} のキャッシュファイルを削除しました。',
  'app_cache_none': '削除できるアプリキャッシュはありません。',
  'max_cache_size': '一時キャッシュ上限',
  'check': '確認',
  'check_updates': '更新を確認',
  'auto_check_updates': '更新を自動チェック',
  'check_updates_subtitle_latest': '現在は最新バージョンです：{version}',
  'checking_updates': 'GitHub の最新バージョンを確認しています...',
  'latest_version_available': '新しいバージョンがあります',
  'open_release_page': 'リリースページを開く',
  'current_version_label': '現在のバージョン：{version}',
  'latest_version_label': '最新バージョン：{version}',
  'update_available_subtitle': '更新があります：{version}',
  'download_update': '更新をダウンロード',
  'downloading_update': '更新をダウンロード中：{percent}%',
  'no_updates_available': '現在は最新バージョンです。',
  'update_no_compatible_release': '現在利用できる互換性のある安定版はありません。',
  'update_missing_asset': '最新バージョンにこのプラットフォーム用のインストーラーがありません。',
  'update_missing_checksum': '最新バージョンに SHA-256 チェックサムファイルがありません。',
  'update_check_failed': '更新確認に失敗しました。後でもう一度お試しください。',
  'update_check_failed_next_step':
      'ネットワーク接続または GitHub へのアクセス状態を確認してから、もう一度お試しください。',
  'update_download_failed': '更新のダウンロードに失敗しました。ネットワークを確認してください。',
  'update_download_failed_next_step':
      '更新のダウンロードまたは SHA-256 検証が完了しませんでした。再試行するか、GitHub Release ページから手動でダウンロードしてください。',
  'update_install_preparing_title': '更新を準備しています',
  'update_install_preparing_message':
      'バージョン {version} をダウンロードし、SHA-256 検証に合格しました。更新を完了するため、アプリが自動で終了して再起動する場合があります。ファイル：{path}',
  'update_ready_install': 'インストーラーを開きました。画面の指示に従って更新してください。',
  'update_install_failed': '更新のインストールを続行できませんでした。',
  'update_install_failed_next_step':
      '後でもう一度お試しください。まだ失敗する場合は更新ログを確認するか、GitHub Release ページから手動でインストールしてください。',
  'update_install_failed_with_detail':
      '後でもう一度お試しください。まだ失敗する場合は更新ログを確認してください。詳細: {detail}',
  'open_update_log': 'ログを表示',
  'install_permission_needed': 'このアプリから不明なアプリをインストールする許可を有効にしてください。',
  'install_permission_title': 'アップデートのインストールを許可',
  'install_permission_message':
      '新しいバージョンのダウンロードとインストールを続けるには、このアプリから不明なアプリをインストールする許可が必要です。今すぐ設定を開きますか？',
  'transcode_defaults': '変換の既定値',
  'format': '形式',
  'bitrate': 'ビットレート',
  'bitrate_used': 'MP3 / AAC / OGG 出力でこのビットレートを使用します。',
  'bitrate_not_used': '{format} は形式内蔵のエンコードを使うため、ビットレート設定は無効です。',
  'about': 'このアプリについて',
  'about_subtitle': 'バージョン、開発者、プロジェクト情報',
  'app_desc': '並行セッションと高音質再生に対応。',
  'about_version': 'バージョン',
  'about_source_code': 'ソースコード',
  'about_wiki': 'Wiki',
  'about_wiki_open_failed': 'GitHub のプロジェクトページを開けませんでした。',
  'about_author': '開発者',
  'about_reward': 'プロジェクトを支援',
  'about_reward_open_failed': '愛発電の支援ページを開けませんでした。',
  'language': '言語',
  'interface_language': '表示言語',
  'follow_system': 'システムに従う',
  'startup_page': '起動画面',
  'portrait_lock': '縦画面固定',
  'startup_page_asmrOne': 'ASMR.ONE',
  'startup_page_library': '音声ライブラリ',
  'startup_page_playlist': 'プレイリスト',
  'allow_duplicate_works': '同じ作品の重複を許可',
  'reduce_animations': 'アニメーションを減らす',
  'haptic_feedback_enabled': '操作時のバイブレーション',
  'dlsite_metadata_language': 'DLsite メタデータの言語',
  'timer_title': 'タイマー',
  'set_countdown': 'カウントダウン設定',
  'sleep_mode': 'スリープモード',
  'sleep_mode_auto_trigger': 'スリープモード',
  'sleep_mode_auto_trigger_subtitle': 'おやすみキャンバスに入るトリガー条件',
  'sleep_mode_auto_trigger_manual': '手動',
  'sleep_mode_auto_trigger_afterPlayback5min': '再生開始5分後',
  'sleep_mode_auto_trigger_afterCountdown5min': 'カウントダウン開始5分後',
  'sleep_canvas': 'おやすみキャンバス',
  'stop_after_current_track': '現在のトラック終了後に停止',
  'stop_after_current_track_subtitle': '現在のトラックが終了した後に自動停止',
  'hold_to_exit_sleep_mode': '長押しで終了',
  'no_timer_set': 'タイマー未設定',
  'sleep_countdown': 'スリープタイマー',
  'double_tap_to_play_pause': 'ダブルタップで再生 / 一時停止',
  'swipe_to_adjust_track_volume': '上下で音量微調整',
  'start_mode': '開始方法',
  'confirm_start_now': '確定してすぐ開始',
  'confirm_wait_playback': '確定して再生開始を待つ',
  'set_duration_first': '先にカウントダウン時間を設定してください。',
  'cancel_timer': 'タイマー解除',
  'auto_resume_after_timer': '再生の予約再開',
  'auto_resume_subtitle': '指定時刻に再生を自動再開します。',
  'resume_time': '再開時刻：{time}',
  'tap_choose_resume_time': 'タップして自動再開時刻を選択',
  'choose_auto_resume_time': '自動再開時刻を選択',
  'set_timer_to_enable_auto_resume': 'カウントダウンを設定すると、ここで自動再開を有効にできます。',
  'wait_play_trigger': '再生トリガー待機',
  'manual_start': 'すぐに開始',
  'auto_start_after_play': '音声再生後に自動開始',
  'countdown_finished': 'カウントダウン終了',
  'waiting_to_start_countdown': '再生開始後にカウント開始',
  'counting_down': 'カウントダウン中',
  'waiting_for_auto_resume': '自動再開を待機中',
  'paused_audio_count': '{count} 件の音声を一時停止しました。',
  'auto_resume_at': '{time} に自動再開します。',
  'hour': '時',
  'minute': '分',
  'second': '秒',
  'manual_start_subtitle': 'すぐにカウントダウンを開始します。',
  'trigger_start_subtitle': '再生検出時にカウントダウンを開始します。',
  'selected_file': '選択済み：{name}',
  'select_video_and_output': '先に動画ファイルと出力先を選択してください。',
  'conversion_starting': '変換を開始…',
  'converting_percent': '変換中：{percent}%',
  'conversion_done_saved': '変換完了、保存先：{path}',
  'video_conversion_completed': '動画から音声への変換完了',
  'video_conversion_failed_title': '動画から音声への変換に失敗',
  'conversion_canceled': '変換をキャンセルしました。',
  'conversion_failed': '変換に失敗しました。再試行してください。',
  'canceling_conversion': '変換をキャンセル中…',
  'source_video_file': '動画ファイル',
  'tap_select_video_file': '変換する動画ファイルを選択',
  'output_directory': '出力先',
  'tap_select_output_dir': '音声の保存先を選択',
  'current_params': '現在の設定：{value}',
  'format_auto_encode': '形式に合わせて自動エンコード',
  'cancel_conversion': '変換をキャンセル',
  'notification_permission_title': '通知を許可',
  'notification_permission_message':
      'このアプリの通知が無効なため、通知シェードに再生操作を表示できません。アプリ通知とメディア通知を有効にしてください。',
  'notification_permission_enabled': '通知権限が有効になりました。',
  'background_play_permission_title': 'バックグラウンド再生を許可',
  'background_play_permission_message':
      '画面オフ後も音声を再生し続けるために、アプリを電池制限の対象外に設定してください。設定画面を開きますか？',
  'manage_files_permission_title': 'すべてのファイルへのアクセスを許可',
  'manage_files_permission_message':
      'このアプリにはまだすべてのファイルへのアクセスがありません。フォルダやライブラリの追加、ローカルメディアの読み取りに失敗する可能性があります。今すぐ設定を開きますか？',
  'manage_files_permission_enabled': 'すべてのファイルへのアクセスを許可しました。',
  'go_settings': '設定を開く',
  'later': 'あとで',
  'start_conversion': '変換開始',
  'choose_library': 'ライブラリを追加',
  'choose_library_folder': 'ライブラリフォルダを選択',
  'import_library_done':
      'ライブラリの取り込みが完了しました。{folderCount} 個のルートフォルダと {count} 件の音声を追加しました。',
  'no_child_folder_found': '選択したフォルダの直下に取り込める子フォルダがありません。',
  'edit_library': 'ライブラリ編集',
  'edit_library_hint': '追加済みライブラリ、フォルダ、音声を管理します',
  'library_removed': 'ライブラリを削除しました。',
  'remove_library': 'ライブラリを削除',
  'remove_library_confirm': 'このライブラリと追加済みフォルダを削除しますか？\n\n{name}',
  'excluded': '除外済み',
  'restore': '復元',
  'exclude': '除外',
  'library_edit_empty': '追加済みライブラリはありません。',
  'subtitle_window_settings': '字幕オーバーレイ',
  'subtitle_window_preview': 'ライブプレビュー',
  'subtitle_preview_sample': '波の音がゆっくり近づき、呼吸も少しずつ落ち着いていきます。',
  'font_setting': 'フォント設定',
  'system_default': 'システム標準',
  'font_color': 'テキスト色',
  'background_opacity': '背景透明度',
  'background_transparency': '背景透明度',
  'background_color': '背景色',
  'reset_to_default': 'デフォルトにリセット',
  'restore_default': 'デフォルトに戻す',
  'turn_on_subtitle': '字幕を表示',
  'turn_off_subtitle': '字幕を非表示',
  'subtitle_global_display': '字幕を全体に表示',
  'overlay_permission_title': '字幕用オーバーレイを許可',
  'overlay_permission_message':
      '字幕のグローバル表示を有効にするには、このアプリにオーバーレイ表示を許可する必要があります。これにより、他のページやバックグラウンドでも字幕を表示し続けられます。今すぐ設定を開きますか？',
  'border_depth': '枠線の太さ',
  'font_size': 'フォントサイズ',
  'volume': '音量',
  'volume_range_hint': '0-150',
  'playback_speed': '再生速度',
  'volume_balance': 'L/R バランス',
  'speed_reset': '1.0x に戻す',
  'segment_add': '区間ラベルを追加',
  'segment_start': '開始',
  'segment_end': '終了',
  'segment_name': 'ラベル名',
  'segment_default_name': 'ラベル{index}',
  'segment_name_hint': 'ラベル名を入力',
  'segment_time_input_title': '時刻を入力',
  'segment_delete_title': '区間ラベルを削除',
  'segment_delete_confirm': '「{name}」を削除しますか？',
  'segment_loop': '区間をリピート',
  'volume_warning_title': '音量警告',
  'volume_warning_message': '音量ブーストはクリッピングや歪みの原因になることがあります。',
  'exact_alarm_permission_title': '正確なアラームを許可',
  'exact_alarm_permission_message':
      '画面オフ・バックグラウンド・長時間後の自動再開を安定させるため、このアプリに正確なアラームを許可することをおすすめします。',
  'open_exact_alarm_settings': '正確なアラーム設定を開く',
  'timer_reliability_checking': 'タイマーのバックグラウンド信頼性を確認しています…',
  'timer_reliability_ready': 'バックグラウンド再開の条件は満たされています',
  'timer_reliability_missing': '安定性を高めるため、バックグラウンド実行とタイマー関連の権限を確認してください。',
  'add_playback_queue': '再生キューを作成',
  'default_playback_queue_name': '再生キュー {number}',
  'edit_playback_queue': '再生キューを編集',
  'edit_queue_audio': 'キューの音声を編集',
  'edit_queue_name': 'キュー名を編集',
  'edit_queue_color': 'キューの色を編集',
  'remove_queue': 'キューを削除',
  'remove_queue_confirm': 'この再生キューを削除しますか？',
  'queue_added_audio': 'キューに追加済み',
  'playback_list_audio': '再生リストの音声',
  'add_audio_to_queue': '音声をキューに追加',
  'add_work_to_queue': '作品をキューに追加',
  'empty_playback_queue': 'キューに音声がありません',
  'queue_add_audio_first': '先に音声をキューへ追加してください',
  'edit': '編集',
  'save': '保存',
  'multi_select': '複数選択モード',
  'batch_add_to_playlist': 'プレイリストに追加',
  'batch_added_to_playlist': '{count} 件の作品をプレイリストに追加しました',
  'batch_download': '一括ダウンロード',
  'batch_favorite': '一括お気に入り',
  'batch_unfavorite': '一括お気に入り解除',
  'selected_count': '{count}件 選択中',
};
