const Map<String, String> appLanguageEn = {
  'app_title': 'Doujin Audio',
  'startup_initializing': 'Starting Doujin Audio…',
  'startup_error_title': 'Doujin Audio could not start',
  'startup_error_message':
      'Your local data is safe. Retry startup or export a diagnostic report.',
  'permission_group_playback': 'Playback basics',
  'permission_group_reliability': 'Timer & reliability',
  'permission_group_advanced': 'Advanced features',
  'onboarding_title': 'Doujin Audio',
  'onboarding_subtitle': 'A local-first player for ASMR and voice libraries.',
  'onboarding_local':
      'Your audio library and playback state stay on this device.',
  'onboarding_online_optional':
      'ASMR.ONE and other online features are always optional.',
  'onboarding_permissions':
      'Permissions are requested only when you use the related feature.',
  'onboarding_start': 'Get started',
  'privacy_summary_action': 'View privacy summary',
  'privacy_summary_title': 'Privacy summary',
  'privacy_summary_local_title': 'Local by default',
  'privacy_summary_local_body':
      'Your library, settings, and playback state are stored on this device.',
  'privacy_summary_network_title': 'Optional network features',
  'privacy_summary_network_body':
      'Network access is used only for features such as ASMR.ONE, metadata, and app updates.',
  'privacy_summary_diagnostics_title': 'Diagnostics stay in your control',
  'privacy_summary_diagnostics_body':
      'Sanitized diagnostics are created only when you choose to export them.',
  'nav_library': 'Audio library',
  'open_library': 'Open library',
  'open_playback_details': 'Open playback details',
  'retry_playback': 'Retry playback',
  'nav_sessions': 'Playlist',
  'nav_settings': 'Settings',
  'timer': 'Timer',
  'done': 'Done',
  'close': 'Close',
  'fullscreen': 'Fullscreen',
  'exit_fullscreen': 'Exit fullscreen',
  'brightness': 'Brightness',
  'seek_backward_five_seconds': 'Rewind 5s',
  'seek_forward_five_seconds': 'Forward 5s',
  'temporary_double_speed': 'Temporary 2.0×',
  'open_timer_settings': 'Open timer settings',
  'timer_play_plus': 'Play + {time}',
  'asmr_player': 'NL Audio',
  'music_library': 'Audio library',
  'playback_sessions': 'Playlist',
  'pin_to_top': 'Pin to Top',
  'unpin_from_top': 'Unpin',
  'pinned_to_top': 'Pinned',
  'settings': 'Settings',
  'asmr_header_stats': '{count} works included',
  'library_header_stats': '{works} works  {sessions} sessions',
  'playlist_header_stats': '{sessions} sessions  {playing} playing',
  'video_to_audio': 'Video to audio',
  'import_audio': 'Add audio',
  'import_folder': 'Add folder',
  'import_file': 'Add file',
  'import_library': 'Add library',
  'refresh_watched_folder': 'Refresh watched folders',
  'more_actions': 'More actions',
  'sort_by': 'Sort by',
  'sort_by_title': 'Sort by',
  'sort_description': 'Description',
  'sort_name': 'Name',
  'sort_voice_actor': 'Voice actor',
  'sort_duration': 'Duration',
  'sort_release_date': 'Release time',
  'sort_added_date': 'Added time',
  'sort_playback_time': 'Playback time',
  'sort_ascending': 'Ascending',
  'sort_descending': 'Descending',
  'sort_group_by_library': 'Group by library',
  'batch_metadata': 'Batch metadata completion',
  'batch_metadata_hint':
      'Fetch ASMR.ONE work information first, then fall back to DLsite. Review each work before moving to the next one.',
  'batch_metadata_no_metadata': 'Works missing all data',
  'batch_metadata_any_missing': 'Works with missing data',
  'batch_metadata_has_rj_code': 'Works with an RJ code',
  'batch_metadata_specific': 'Specify works',
  'batch_metadata_picker_search': 'Search RJ code or title',
  'batch_metadata_picker_done': 'Done ({count})',
  'batch_metadata_all': 'All data',
  'batch_metadata_start': 'Start completing metadata',
  'batch_metadata_status_searching': 'Searching',
  'batch_metadata_status_found': 'Found (unconfirmed)',
  'batch_metadata_status_confirmed': 'Found (confirmed)',
  'batch_metadata_status_not_found': 'Not found',
  'batch_metadata_status_failed': 'Search failed',
  'batch_metadata_status_excluded': 'Excluded',
  'batch_metadata_action_exclude': 'Exclude',
  'batch_metadata_action_restore': 'Restore',
  'batch_metadata_progress': '{current} / {total}',
  'batch_metadata_load_failed':
      'Unable to load the local library. Please try again.',
  'batch_metadata_completion_title': 'Batch completion finished',
  'batch_metadata_completion_saved': 'Saved {count} work data entries',
  'batch_metadata_completion_skipped': 'Skipped {count} work data entries',
  'batch_metadata_completion_failed': 'Failed {count} work data entries',
  'library_manage_empty': 'No imported libraries yet.',
  'skip': 'Skip',
  'search': 'Search',
  'search_audio_placeholder': 'Search audio...',
  'scanning_title': 'Scanning',
  'loading_dot': 'Loading...',
  'playback_loading': 'Loading',
  'playback_state_playing': 'Playing',
  'playback_state_paused': 'Paused',
  'playback_failed_retry': 'Playback failed. Tap the play button to retry.',
  'playback_network_failed_retry':
      'Network connection failed. Tap play to retry',
  'asmr_playback_load_failed_retry': 'Loading failed. Tap to retry',
  'asmr_playback_network_failed_retry':
      'Network connection failed. Tap to retry',
  'asmr_network_failed_retry':
      'Network connection failed. Pull down to try again.',
  'asmr_authentication_failed_retry':
      'Your session has expired. Sign in and try again.',
  'scan_cancel': 'Cancel scan',
  'scan_cancelled': 'Scan cancelled.',
  'scan_stage_preparing': 'Reading folder...',
  'scan_stage_enumerating': 'Finding audio files...',
  'scan_stage_merging': 'Loading track information...',
  'scan_stage_saving': 'Saving library...',
  'scan_stage_covers': 'Loading covers...',
  'scan_processed': '{processed} items processed',
  'scan_processed_total': '{processed} / {total} items processed',
  'scan_current_folder': 'Current folder',
  'scan_found': 'Found',
  'scan_duplicate': 'Duplicate',
  'scan_failure': 'Failed',
  'audio_count': '{count} tracks',
  'folder_count': '{count} folders',
  'no_audio_files': 'No audio files yet',
  'no_audio_found': 'No audio files found.',
  'no_search_results': 'No matching results',
  'search_try_another_term': 'Try another term or clear the current search.',
  'search_match_count': '{match} / {total} tracks matched',
  'import_audio_hint':
      'Use the buttons below to add audio from a folder or individual file.',
  'need_storage_permission_scan_folder':
      'Storage permission is required to scan folders.',
  'need_storage_permission_import_audio':
      'Storage permission is required to import audio.',
  'import_audio_failed': 'Unable to add audio. Please try again.',
  'import_failed_next_step':
      'Check that the selected file or folder is still accessible, then try again.',
  'scan_failed_next_step':
      'Check storage permission and whether the source folder still exists, then retry.',
  'detail_backup_import_failed':
      '{count} detail backups could not be synchronized. Check doujin-audio.json and retry.',
  'refresh_done_added': 'Refresh complete: {count} new tracks added.',
  'refresh_done_no_new': 'No new audio found.',
  'asmr_refresh_done_updated': 'Category content updated.',
  'asmr_online_playback': 'ASMR.ONE Online Playback',
  'asmr_online_optional_notice':
      'ASMR.ONE is optional and connects to the network only while you use it.',
  'asmr_refresh_no_updates': 'No new updates found.',
  'asmr_refresh_failed': 'Sync failed. Pull down to try again.',
  'asmr_favorite_added': 'Added to favorites.',
  'asmr_favorite_removed': 'Removed from favorites.',
  'asmr_category_sales': 'Sales',
  'asmr_category_rating': 'Rating',
  'asmr_category_reviews': 'Reviews',
  'asmr_category_release': 'Release',
  'asmr_category_collected': 'Date collected',
  'asmr_category_recommendation': 'Recommendations',
  'asmr_category_favorites': 'Favorites',
  'asmr_category_history': 'History',
  'asmr_account_menu': 'Account',
  'asmr_account_title': 'ASMR.ONE Account',
  'asmr_account_restoring': 'Restoring account information…',
  'asmr_login_title': 'Login',
  'asmr_login_account': 'Account',
  'asmr_login_password': 'Password',
  'asmr_login_action': 'Login',
  'asmr_logout_action': 'Logout',
  'asmr_logged_in_as': 'Logged in as {name}',
  'asmr_login_success': 'Logged in.',
  'asmr_logout_success': 'Logged out.',
  'asmr_login_failed': 'Login failed. Check the account and password.',
  'asmr_token_expired': 'Login expired. Please log in again.',
  'asmr_account_sync_now': 'Sync now',
  'asmr_account_syncing': 'Syncing account data...',
  'asmr_account_sync_done': 'Account data synced.',
  'asmr_account_sync_failed': 'Account sync failed. Try again later.',
  'asmr_account_not_synced': 'Not synced yet.',
  'asmr_account_last_sync': 'Last sync: {time}',
  'asmr_account_pending_count': '{count} changes pending sync',
  'asmr_categories_title': 'Categories',
  'follow_interface_language': 'Same as app',
  'asmr_page_language': 'ASMR.ONE language',
  'asmr_language_zh': 'Chinese',
  'asmr_language_ja': 'Japanese',
  'asmr_language_en': 'English',
  'asmr_search_hint': 'Search works...',
  'asmr_empty_category': 'No content in this category yet.',
  'asmr_load_more_hint': 'Pull up to load more',
  'asmr_add_to_playlist': 'Add to playlist',
  'add_to_playlist': 'Add to playlist',
  'asmr_added_to_playlist': 'Added to playlist: {title}',
  'asmr_detail_action': 'Details',
  'asmr_detail_tooltip': 'View work details',
  'asmr_favorite_action': 'Favorite',
  'asmr_unfavorite_action': 'Unfavorite',
  'asmr_add_favorite_tooltip': 'Add to favorites',
  'asmr_download_action': 'Download',
  'asmr_download_work_tooltip': 'Download work',
  'asmr_empty_track_tree': 'This work has no expandable audio tree.',
  'asmr_circle_label': 'Circle',
  'asmr_tags_label': 'Tags',
  'asmr_detail_title': 'Details',
  'asmr_detail_readonly_hint':
      'Read-only mode. Editing and drag sorting are not supported.',
  'asmr_detail_load_failed':
      'Failed to load work information. Please try again later.',
  'asmr_detail_basic_info': 'Basic Information',
  'asmr_detail_other': 'Other information',
  'asmr_detail_statistics': 'Statistics',
  'asmr_detail_release_date': 'Release date',
  'asmr_detail_duration': 'Playback duration',
  'asmr_detail_sales': 'Sales',
  'asmr_detail_rating': 'Rating',
  'asmr_detail_unrated': 'Unrated',
  'asmr_detail_reviews': 'Reviews',
  'asmr_detail_age_rating': 'Age rating',
  'asmr_detail_language_editions': 'Language editions',
  'asmr_detail_description': 'Synopsis',
  'asmr_unknown_circle': 'Unknown circle',
  'asmr_missing_rj': 'No RJ number',
  'asmr_has_subtitle': 'Includes subtitles',
  'asmr_unknown': 'Unknown',
  'asmr_download_title': 'Download',
  'asmr_download_choose_path': 'Choose path',
  'asmr_download_change_path': 'Change path',
  'asmr_download_path_missing':
      'The saved download path no longer exists. Choose a new path.',
  'asmr_download_conflict_title': 'Handle duplicate names',
  'asmr_download_conflict_message':
      'What should happen if the target path has a file or folder with the same name?',
  'asmr_download_conflict_skip': 'Skip',
  'asmr_download_conflict_overwrite': 'Overwrite',
  'asmr_download_task_running': 'A download task is already running',
  'asmr_download_select_required': 'Select files or folders to download first',
  'asmr_download_completed_with_failures':
      'Download completed, but some files failed',
  'asmr_download_failed': 'Download failed: {error}',
  'asmr_download_failed_title': 'Download failed',
  'asmr_download_failed_next_step':
      'Check the destination folder and network connection, then retry.',
  'asmr_download_starting': 'Downloading',
  'asmr_download_confirm': 'Confirm download',
  'asmr_download_added_to_list': 'Added to download list',
  'asmr_download_task_title': 'Download tasks',
  'asmr_download_task_not_found': 'Download task not found',
  'asmr_download_details_title': 'Download details',
  'asmr_download_no_files_selected': 'No files selected',
  'asmr_download_remove_task': 'Remove download task',
  'asmr_download_remove_entry': 'Remove task entry',
  'asmr_download_remove_and_delete': 'Also delete downloaded content',
  'asmr_download_no_tasks': 'No download tasks',
  'asmr_download_waiting': 'Waiting',
  'asmr_download_status': 'Status',
  'asmr_download_destination': 'Destination',
  'asmr_download_progress': 'Progress',
  'asmr_download_skipped': 'Skipped',
  'asmr_download_failed_count': 'Failed',
  'asmr_download_downloaded': 'Downloaded',
  'asmr_download_total_size': 'Total size',
  'asmr_download_task_removed': 'Task entry removed',
  'asmr_download_task_removed_and_deleted':
      'Task removed and downloaded content deleted',
  'asmr_download_summary_selected': '{count} files selected, {size} total.',
  'asmr_download_empty_folder': 'Empty folder',
  'asmr_download_status_preparing': 'Preparing',
  'asmr_download_status_downloading': 'Downloading',
  'asmr_download_status_retrying': 'Retrying ({attempt}/{max})',
  'asmr_download_status_paused': 'Paused',
  'asmr_download_status_completed': 'Completed',
  'asmr_download_status_failed': 'Failed',
  'asmr_download_status_idle': 'Waiting',
  'refresh': 'Refresh',
  'downloads': 'Downloads',
  'choose_music_folder': 'Choose music folder',
  'import_done_added': 'Added {count} new tracks.',
  'library_folder_exists': 'Duplicate folder exists.',
  'library_exists': 'Duplicate library exists.',
  'library_file_exists': 'Duplicate file exists.',
  'choose_audio_files': 'Choose audio files',
  'imported_files': 'Imported files',
  'manually_selected_files': 'Manually selected files',
  'file_added': 'File added',
  'library_category_all': 'All',
  'library_category_tags': 'Tags',
  'library_category_voice_actors': 'Voice',
  'library_category_circles': 'Circles',
  'library_category_no_tags': 'No tag information yet',
  'library_category_no_voice_actors': 'No voice actor information yet',
  'library_category_no_circles': 'No circle information yet',
  'library_category_no_matches': 'No matching audio',
  'copied_to_clipboard': 'Copied to clipboard: {value}',
  'remove_folder': 'Remove folder',
  'remove_folder_confirm':
      'Remove this folder and all audio in it from the library?\n\n{name}',
  'cancel': 'Cancel',
  'remove': 'Remove',
  'removed_prefix': 'Removed: {name}',
  'session_created': 'Created session: {name}',
  'items_count': '{count} items',
  'play_first': 'Play first track',
  'remove_audio_folder': 'Remove folder',
  'play': 'Play',
  'create_another_session': 'Create another session',
  'remove_audio': 'Remove audio',
  'audio_detail': 'Details',
  'audio_detail_title': 'Details',
  'audio_detail_library_root': 'Library root folder',
  'audio_detail_single_file': 'Single imported audio',
  'audio_detail_cover_image': 'Cover image',
  'audio_detail_folder_name': 'Folder name',
  'audio_detail_file_name': 'File name',
  'audio_detail_rj_code': 'RJ number',
  'audio_detail_work_title': 'Work title',
  'audio_detail_circle_name': 'Circle',
  'audio_detail_voice_actors': 'Voice actors',
  'audio_detail_tags': 'Tags',
  'audio_detail_release_date': 'Release date',
  'audio_detail_sales_count': 'Sales',
  'audio_detail_rating': 'Rating',
  'audio_detail_empty': 'Not filled',
  'audio_detail_edit_title': 'Edit {name}',
  'audio_detail_multi_hint':
      'Separate multiple items with the Chinese comma "，"',
  'audio_detail_backup_failed':
      'Saved to the database, but local backup failed.',
  'audio_detail_cover_portability_skipped':
      'The cover exceeds 8 MiB. Its local path was kept, but it was not included in the portable backup.',
  'audio_detail_restored_from_backup': 'Restored from local backup.',
  'audio_detail_rj_format_hint':
      'RJ number should usually look like RJ + digits.',
  'audio_detail_save_failed': 'Save failed. Please try again.',
  'audio_detail_load_failed': 'Load failed. Please try again.',
  'audio_detail_duration_calculation_failed':
      'Unable to calculate duration. Please try again.',
  'audio_detail_fetch_info': 'Fetch info',
  'audio_detail_fetch_scope_title': 'Choose fetch range',
  'audio_detail_fetch_scope_hint':
      'ASMR.ONE is checked first, then DLsite is used as a fallback. Choose which fields to write.',
  'audio_detail_fetch_scope_all_hint':
      'Overwrite current details with the fetched metadata.',
  'audio_detail_fetch_scope_missing_hint':
      'Only fill empty details and keep existing values unchanged.',
  'metadata_scope_missing': 'Missing data',
  'audio_detail_fetch_missing_query':
      'Fill in an RJ number, folder/file name, or work title first.',
  'audio_detail_cover_swipe_hint': 'Swipe left or right to change',
  'audio_detail_set_cover': 'Set as cover',
  'audio_detail_current_cover': 'Current cover',
  'audio_detail_rename_file': 'Rename file',
  'audio_detail_rename_failed':
      'Rename failed. Check whether the file exists or is in use.',
  'dlsite_review_title': 'Review work data',
  'dlsite_save_cover': 'Save cover to folder',
  'dlsite_fetch_failed':
      'Failed to fetch work data. Check the RJ number, folder/file name, work title, or network and try again.',
  'dlsite_cover_save_failed':
      'Info was saved, but the cover could not be saved.',
  'confirm': 'Confirm',
  'retry': 'Retry',
  'undo': 'Undo',
  'items_removed_count': '{count} items removed',
  'removal_failed': 'Some items could not be removed. Please try again.',
  'previous': 'Previous',
  'next': 'Next',
  'clear_all_sessions': 'Clear all sessions',
  'stop_remove_all_sessions': 'Stop and remove all running playback sessions?',
  'clear': 'Clear',
  'all_sessions_cleared': 'All sessions were cleared.',
  'audio_removed': 'Audio removed.',
  'audio_excluded': 'Audio excluded from library.',
  'folder_audio_removed': 'Audio removed from the folder.',
  'folder_removed': 'Folder removed.',
  'folder_excluded': 'Folder excluded from library.',
  'pause_all_sessions': 'Pause all sessions',
  'all_paused': 'All sessions were paused.',
  'no_active_sessions': 'No active sessions',
  'go_library_hint':
      'Play audio in Library first, then create concurrent sessions.',
  'single_loop': 'Single loop',
  'pause_after_playback': 'Pause after one round',
  'loop_mode_title': 'Playback mode',
  'sequential_playback': 'Sequential',
  'loop_playback': 'Sequential',
  'shuffle_playback': 'Shuffle',
  'cross_folder': 'Cross-folder',
  'current_folder': 'Current folder',
  'random_order': 'Random',
  'sequential_order': 'Sequential',
  'no_other_audio_in_folder': 'No other audio available in this folder.',
  'switch_audio': 'Switch audio',
  'channel_swap': 'Channel Swap',
  'channel_swap_desc': 'Swap audio channels.',
  'volume_normalization': 'Volume Normalization',
  'volume_normalization_desc': 'Limit sudden loud sounds and equalize volume.',
  'skip_silence': 'Skip silence',
  'skip_silence_desc': 'Shorten silent segments.',
  'noise_reduction': 'Noise reduction',
  'noise_reduction_desc': 'Reduce sharp background noise.',
  'audio_features': 'Features',
  'equalizer': 'Equalizer',
  'time_segments': 'Segments',
  'equalizer_supported': 'Adjust using this device’s available bands.',
  'equalizer_enable_hint': 'Turn on EQ to load supported device bands.',
  'equalizer_unavailable':
      'This device has not returned EQ bands yet. Turn EQ on and wait briefly.',
  'eq_preset': 'Preset',
  'eq_reset': 'Reset',
  'eq_save_preset': 'Save preset',
  'eq_delete_preset': 'Delete preset',
  'eq_preset_name': 'Preset name',
  'mute': 'Mute',
  'unmute': 'Unmute',
  'eq_preset_flat': 'Flat',
  'eq_preset_asmr_immersive': 'ASMR Immersive',
  'eq_preset_voice_clear': 'Voice Clear',
  'eq_preset_ear_massage': 'Ear Massage',
  'eq_preset_night_soft': 'Night Soft',
  'eq_preset_bass_boost': 'Bass Boost',
  'previous_track': 'Previous',
  'pause': 'Pause',
  'resume': 'Resume',
  'next_track': 'Next',
  'collapse': 'Collapse',
  'expand': 'Expand',
  'end_session': 'End session',
  'random_play': 'Random play',
  'sequential_play': 'Sequential play',
  'cross_folder_play': 'Cross-folder play',
  'current_folder_only': 'Current folder only',
  'dark_mode': 'Appearance',
  'cover_image_resolution': 'Cover quality',
  'cover_image_resolution_300': '300px',
  'cover_image_resolution_600': '600px',
  'cover_image_resolution_900': '900px',
  'cover_image_resolution_1200': '1200px',
  'cover_image_resolution_original': 'Original',
  'cover_image_display_mode': 'Cover display mode',
  'cover_image_display_mode_fill': 'Fill',
  'cover_image_display_mode_stretch': 'Stretch',
  'cover_image_display_mode_tile': 'Fit with blurred backdrop',
  'prefer_embedded_audio_cover': 'Prefer embedded audio covers',
  'theme_system': 'System',
  'theme_light': 'Light',
  'theme_dark': 'Dark',
  'black_theme': 'Pure black theme',
  'differentiate_asmr_theme': 'Separate ASMR.ONE colors',
  'app_theme_color': 'App theme color',
  'asmr_theme_color': 'ASMR.ONE theme color',
  'theme_color_coral': 'Coral',
  'theme_color_rose': 'Rose',
  'theme_color_pink': 'Pink',
  'theme_color_lavender': 'Lavender',
  'theme_color_periwinkle': 'Periwinkle',
  'theme_color_blue': 'Blue',
  'theme_color_sky': 'Sky blue',
  'theme_color_cyan': 'Cyan',
  'theme_color_mint': 'Mint',
  'theme_color_green': 'Green',
  'theme_color_light_green': 'Light green',
  'theme_color_lime': 'Lime',
  'theme_color_amber': 'Amber',
  'theme_color_orange': 'Orange',
  'theme_color_peach': 'Peach',
  'theme_color_gray': 'Gray',
  'playback_detail_subtitle_style': 'Playback detail subtitles',
  'playback_detail_subtitle_style_compact': 'Compact subtitles',
  'playback_detail_subtitle_style_timeline': 'Timeline subtitles',
  'seek_to_subtitle': 'Seek to this subtitle',
  'blur_player_background': 'Blur player background',
  'ui_blur_effect': 'Glass effect',
  'multi_thread_playback': 'Play multiple tracks',
  'allow_video_playback': 'Allow video playback',
  'notification_bar': 'Playback notification controls',
  'show_playback_card': 'Show playback card',
  'section_detail_info': 'Details',
  'card_info_display': 'Card details',
  'card_info_display_subtitle': '{count} of {max} selected',
  'card_info_none': 'None',
  'card_info_release_date': 'Release',
  'card_info_sales_count': 'Sales',
  'card_info_rating': 'Rating',
  'card_info_duration': 'Duration',
  'auto_play_added_sessions': 'Play after adding',
  'audio_device_disconnect_behavior': 'When headphones disconnect',
  'audio_device_disconnect_pause': 'Pause',
  'audio_device_disconnect_continuePlayback': 'Continue',
  'audio_focus_strategy': 'Audio focus',
  'audio_focus_strategy_standard': 'Standard',
  'audio_focus_strategy_mixWithOthers': 'Overlap',
  'transient_audio_focus_loss_behavior': 'When other audio interrupts',
  'transient_audio_focus_loss_duck': 'Lower volume',
  'transient_audio_focus_loss_pause': 'Pause',
  'interruption_resume_behavior': 'After a call ends',
  'interruption_resume_stayPaused': 'Stay paused',
  'interruption_resume_resume': 'Resume',
  'asmr_playback_cache': 'Cache ASMR.ONE audio',
  'record_playback_progress': 'Remember playback position',
  'section_language': 'Language',
  'section_language_subtitle': 'Interface and content language',
  'section_common': 'General',
  'section_common_subtitle': 'Startup, behavior, and system options',
  'settings_group_startup_behavior': 'Startup',
  'settings_group_general_behavior': 'General behavior',
  'settings_group_page_display': 'Page display',
  'show_local_library': 'Music library',
  'show_asmr_one': 'ASMR.ONE',
  'settings_group_theme_layout': 'Theme and layout',
  'settings_group_cover_background': 'Cover and background',
  'settings_group_playback_detail': 'Playback detail',
  'settings_group_playback_behavior': 'Playback behavior',
  'settings_group_audio_recovery': 'Audio and recovery',
  'settings_group_download': 'Download',
  'settings_group_download_files': 'Files and naming',
  'settings_group_data': 'Data & Support',
  'settings_group_cache': 'Cache',
  'settings_group_permissions': 'Permissions & Background',
  'settings_group_updates': 'Updates',
  'section_appearance': 'Appearance',
  'section_appearance_subtitle': 'Theme, layout, and subtitle appearance',
  'section_playback': 'Playback',
  'section_playback_subtitle': 'Playback controls, audio, and recovery',
  'section_asmr_download': 'ASMR.ONE Downloads',
  'section_asmr_download_subtitle': 'Download settings and file naming',
  'asmr_download_path_setting': 'Download folder',
  'asmr_download_path_not_set': 'Not set',
  'asmr_download_conflict_setting': 'Existing file handling',
  'asmr_download_retry_count': 'Auto retry count',
  'asmr_download_thread_count': 'Thread count',
  'asmr_download_save_metadata_setting': 'Save work information',
  'asmr_download_save_cover': 'Save cover image',
  'asmr_download_folder_name_setting': 'Folder name',
  'asmr_download_folder_name_hint':
      'Select the fields to use and drag selected fields to reorder them. Keep at least one field.',
  'asmr_download_folder_field_rj_code': 'RJ number',
  'asmr_download_folder_field_voice_actors': 'Voice actors',
  'asmr_download_folder_field_circle_name': 'Circle',
  'asmr_download_folder_field_work_title': 'Work title',
  'section_data_storage': 'Data & Storage',
  'section_data_storage_subtitle': 'Cache and data management',
  'section_updates_permissions': 'Updates & Permissions',
  'section_updates_permissions_subtitle':
      'Permissions, updates, and background access',
  'permission_enabled': 'Enabled',
  'permission_not_enabled': 'Disabled',
  'permission_state_authorized': 'Allowed',
  'permission_state_unauthorized': 'Not allowed',
  'permission_state_restricted': 'Restricted',
  'permission_state_recommended': 'Recommended',
  'system_settings_open_failed':
      'Could not open system settings. Adjust this app manually from system app settings.',
  'permission_notification_description':
      'Shows background playback status and media controls.',
  'permission_background_description':
      'Reduces the chance of some devices restricting playback while the screen is off.',
  'permission_manage_files_description':
      'Only needed for advanced direct filesystem library scans. Prefer the system folder picker.',
  'permission_overlay_description':
      'Only needed to show global subtitles over other apps.',
  'permission_update_install_description':
      'Only used to install GitHub Release updates you explicitly download.',
  'storage_usage_title': 'Storage space',
  'storage_usage_total': 'Total device storage',
  'storage_usage_audio_library': 'Local audio library',
  'storage_usage_app_cache': 'App cache',
  'storage_usage_other': 'Other used space',
  'storage_usage_available': 'Available space',
  'storage_usage_unavailable':
      'Storage information is temporarily unavailable.',
  'storage_usage_retry': 'Reload storage information',
  'operation_completed': 'Completed',
  'operation_failed': 'Operation failed',
  'export_diagnostics': 'Export diagnostics',
  'export_backup': 'Export backup',
  'export_backup_subtitle':
      'Back up app data, playback history, and the ASMR.ONE login account.',
  'restore_backup': 'Restore backup',
  'restore_backup_subtitle':
      'Replace current data completely on the next app start.',
  'backup_sensitive_warning':
      'This unencrypted backup contains the ASMR.ONE account name, password, and login token. Anyone with the file may be able to sign in. Continue?',
  'restore_backup_warning':
      'Restoring replaces all current app data and stops playback. Audio files and folder permissions are not restored. The app must be closed and restarted.',
  'select_backup': 'Select backup',
  'backup_exported': 'Backup exported to {path}',
  'backup_ready_to_restore': 'Backup is ready',
  'backup_restart_required':
      'The backup passed validation and will be restored on the next start. Close and restart the app now.',
  'backup_restore_succeeded':
      'Backup restored. App data and the ASMR.ONE account were updated.',
  'backup_restore_failed_rolled_back':
      'Backup restore failed. The previous app data was restored safely.',
  'unexpected_error_title': 'Doujin Audio encountered an unexpected error',
  'unexpected_error_message':
      'Your local data is safe. Export diagnostics, then close and restart the app.',
  'close_and_restart': 'Close and restart',
  'export_diagnostics_subtitle':
      'Export sanitized logs and diagnostic information.',
  'diagnostics_exported': 'Diagnostic report exported to {path}',
  'operation_failed_retry': 'Operation failed. Please try again.',
  'operation_failed_diagnostics_hint':
      'Try again, or export diagnostics if the problem repeats.',
  'section_danger_zone': 'Other',
  'allow_background_run': 'Allow background run',
  'allow_background_run_subtitle': 'Prevent system restrictions in background.',
  'allow_background_run_ready':
      'This app is already allowed to run in the background. Screen-off playback should be more stable.',
  'allow_background_run_checking': 'Checking background run status...',
  'allow_background_run_open_failed':
      'Could not open background run settings. Please adjust this app manually in system settings.',
  'notification_permission_status': 'Notification permission',
  'notification_permission_ready':
      'Notification permission is enabled, so background controls can stay visible and screen-off playback is more stable.',
  'notification_permission_missing':
      'Notification permission is disabled, so Android may restrict background playback controls and status.',
  'notification_permission_checking': 'Checking notification permission...',
  'notification_settings_open_failed':
      'Could not open notification settings. Please change it manually in system settings.',
  'open_notification_settings': 'Open notification settings',
  'exact_alarm_permission_ready':
      'Exact alarms are available, which improves long-running background auto-resume reliability.',
  'exact_alarm_permission_missing':
      'Exact alarms are disabled, so auto-resume after long background time may be unreliable.',
  'clear_app_cache': 'Clear app cache',
  'clear_app_cache_confirm':
      'This clears cache files created by the app. Library source files will not be deleted. Continue?',
  'app_cache_cleaned': 'Cleared {size} of cached files.',
  'app_cache_none': 'No app cache to clear.',
  'max_cache_size': 'Temporary cache limit',
  'check': 'Check',
  'check_updates': 'Check for updates',
  'auto_check_updates': 'Auto-check updates',
  'check_updates_subtitle_latest':
      'You are already on the latest version: {version}',
  'checking_updates': 'Checking the latest GitHub release...',
  'latest_version_available': 'New version available',
  'open_release_page': 'Open release page',
  'current_version_label': 'Current version: {version}',
  'latest_version_label': 'Latest version: {version}',
  'update_available_subtitle': 'Update available: {version}',
  'download_update': 'Download update',
  'downloading_update': 'Downloading update: {percent}%',
  'no_updates_available': 'You are already on the latest version.',
  'update_no_compatible_release': 'No compatible stable version is available.',
  'update_missing_asset':
      'The latest version is missing an installer for this platform.',
  'update_missing_checksum':
      'The latest version is missing its SHA-256 checksum file.',
  'update_check_failed': 'Update check failed. Please try again later.',
  'update_check_failed_next_step':
      'Check your network connection or GitHub access, then retry.',
  'update_download_failed':
      'Update download failed. Please check your network and try again.',
  'update_download_failed_next_step':
      'The update download or SHA-256 verification did not finish. Retry, or open the GitHub Release page to download it manually.',
  'update_install_preparing_title': 'Preparing update',
  'update_install_preparing_message':
      'Version {version} was downloaded and passed SHA-256 verification. The app may close and restart automatically to finish updating. File: {path}',
  'update_ready_install':
      'The installer is open. Follow the system prompts to finish updating.',
  'update_install_failed': 'Could not continue installing the update.',
  'update_install_failed_next_step':
      'Try again later. If it still fails, check the update log or open the GitHub Release page to install it manually.',
  'update_install_failed_with_detail':
      'Retry later. If it still fails, check the update log. Detail: {detail}',
  'open_update_log': 'View log',
  'install_permission_needed':
      'Please allow this app to install unknown apps first.',
  'install_permission_title': 'Allow update installs',
  'install_permission_message':
      'To keep going with the update download and installation, allow this app to install unknown apps first. Open system settings now?',
  'transcode_defaults': 'Transcode defaults',
  'format': 'Format',
  'bitrate': 'Bitrate',
  'bitrate_used': 'This bitrate will be used for MP3 / AAC / OGG output.',
  'bitrate_not_used':
      '{format} uses built-in encoding parameters. Bitrate setting is ignored.',
  'about': 'About',
  'about_subtitle': 'Version, author, and project information',
  'app_desc': 'Supports concurrent sessions and high-fidelity audio playback.',
  'about_version': 'Version',
  'about_source_code': 'Source code',
  'about_wiki': 'Wiki',
  'about_wiki_open_failed': 'Could not open the GitHub project page.',
  'about_author': 'Author',
  'about_reward': 'Support the project',
  'about_reward_open_failed': 'Could not open the Afdian sponsorship page.',
  'language': 'Language',
  'interface_language': 'Interface language',
  'follow_system': 'Follow system',
  'startup_page': 'Startup page',
  'portrait_lock': 'Portrait lock',
  'startup_page_asmrOne': 'ASMR.ONE',
  'startup_page_library': 'Local audio library',
  'startup_page_playlist': 'Playlist',
  'allow_duplicate_works': 'Allow duplicate works',
  'reduce_animations': 'Reduce animations',
  'haptic_feedback_enabled': 'Haptic feedback',
  'dlsite_metadata_language': 'DLsite metadata language',
  'timer_title': 'Timer',
  'set_countdown': 'Set countdown',
  'sleep_mode': 'Sleep mode',
  'sleep_mode_auto_trigger': 'Sleep mode',
  'sleep_mode_auto_trigger_subtitle':
      'Trigger condition to enter Bedtime Canvas',
  'sleep_mode_auto_trigger_manual': 'Manual',
  'sleep_mode_auto_trigger_afterPlayback5min': '5 min after playback starts',
  'sleep_mode_auto_trigger_afterCountdown5min': '5 min after countdown starts',
  'sleep_canvas': 'Bedtime Canvas',
  'stop_after_current_track': 'Stop after current track',
  'stop_after_current_track_subtitle':
      'Automatically pause and stop after current track finishes',
  'hold_to_exit_sleep_mode': 'Hold to exit',
  'no_timer_set': 'No countdown set',
  'sleep_countdown': 'Sleep timer',
  'double_tap_to_play_pause': 'Double tap to play / pause',
  'swipe_to_adjust_track_volume': 'Swipe up/down for volume',
  'start_mode': 'Start mode',
  'confirm_start_now': 'Confirm and start now',
  'confirm_wait_playback': 'Confirm and wait for playback',
  'set_duration_first': 'Please set a countdown duration first.',
  'cancel_timer': 'Cancel timer',
  'auto_resume_after_timer': 'Scheduled playback resume',
  'auto_resume_subtitle': 'Automatically resume playback at the selected time.',
  'resume_time': 'Resume time: {time}',
  'tap_choose_resume_time': 'Tap to choose auto-resume time',
  'choose_auto_resume_time': 'Choose auto-resume time',
  'set_timer_to_enable_auto_resume':
      'Set a countdown to enable auto-resume here.',
  'wait_play_trigger': 'Wait for playback trigger',
  'manual_start': 'Start now',
  'auto_start_after_play': 'Auto start after audio playback',
  'countdown_finished': 'Countdown finished',
  'waiting_to_start_countdown': 'Waiting for playback to start countdown',
  'counting_down': 'Counting down',
  'waiting_for_auto_resume': 'Waiting for auto-resume',
  'paused_audio_count': '{count} audio items paused',
  'auto_resume_at': 'Auto-resume at {time}',
  'hour': 'Hour',
  'minute': 'Minute',
  'second': 'Second',
  'manual_start_subtitle': 'Start countdown immediately.',
  'trigger_start_subtitle': 'Start countdown on playback.',
  'selected_file': 'Selected: {name}',
  'select_video_and_output':
      'Please select a video file and output directory first.',
  'conversion_starting': 'Starting conversion...',
  'converting_percent': 'Converting: {percent}%',
  'conversion_done_saved': 'Conversion complete. Saved to: {path}',
  'video_conversion_completed': 'Video to audio conversion complete',
  'video_conversion_failed_title': 'Video to audio conversion failed',
  'conversion_canceled': 'Conversion canceled.',
  'conversion_failed': 'Conversion failed. Please try again.',
  'canceling_conversion': 'Canceling conversion...',
  'source_video_file': 'Source video file',
  'tap_select_video_file': 'Tap to choose a video file to convert',
  'output_directory': 'Output directory',
  'tap_select_output_dir': 'Tap to choose where to save the audio',
  'current_params': 'Current settings: {value}',
  'format_auto_encode': 'Automatic format encoding',
  'cancel_conversion': 'Cancel conversion',
  'notification_permission_title': 'Allow notifications',
  'notification_permission_message':
      'Notifications are disabled for this app, so playback controls cannot appear in the notification shade. Enable app notifications and media notifications.',
  'notification_permission_enabled': 'Notifications are now enabled.',
  'background_play_permission_title': 'Allow background playback',
  'background_play_permission_message':
      'To continue playing audio after the screen turns off, this app needs to be exempt from battery optimization. Open settings now?',
  'manage_files_permission_title': 'Allow all-files access',
  'manage_files_permission_message':
      'This app does not have all-files access yet. Adding folders or libraries and reading local media may fail until it is enabled. Open system settings now?',
  'manage_files_permission_enabled': 'All-files access is now enabled.',
  'go_settings': 'Open settings',
  'later': 'Later',
  'start_conversion': 'Start conversion',
  'choose_library': 'Add library',
  'choose_library_folder': 'Choose library folder',
  'import_library_done':
      'Library import complete: {folderCount} root folders and {count} new audio items added.',
  'no_child_folder_found':
      'No importable child folders were found directly inside the selected folder.',
  'edit_library': 'Edit library',
  'edit_library_hint': 'Manage imported libraries, folders, and audio',
  'library_removed': 'Library removed.',
  'remove_library': 'Remove library',
  'remove_library_confirm':
      'Remove this library and all imported folders under it?\n\n{name}',
  'excluded': 'Excluded',
  'restore': 'Restore',
  'exclude': 'Exclude',
  'library_edit_empty': 'No imported libraries yet.',
  'subtitle_window_settings': 'Subtitle window',
  'subtitle_window_preview': 'Live preview',
  'subtitle_preview_sample':
      'The ocean comes closer, and your breathing settles with it.',
  'font_setting': 'Font settings',
  'system_default': 'System default',
  'font_color': 'Text color',
  'background_opacity': 'Background opacity',
  'background_transparency': 'Background transparency',
  'background_color': 'Background color',
  'reset_to_default': 'Reset to default',
  'restore_default': 'Restore default',
  'turn_on_subtitle': 'Turn on subtitle',
  'turn_off_subtitle': 'Turn off subtitle',
  'subtitle_global_display': 'Show subtitles globally',
  'overlay_permission_title': 'Allow subtitle overlay',
  'overlay_permission_message':
      'Before turning on global subtitle display, allow this app to draw over other apps so subtitles can keep showing across pages and in the background. Open system settings now?',
  'border_depth': 'Border thickness',
  'font_size': 'Font size',
  'volume': 'Volume',
  'volume_range_hint': '0-150',
  'playback_speed': 'Speed',
  'volume_balance': 'Balance',
  'speed_reset': 'Reset to 1.0x',
  'segment_add': 'Add segment label',
  'segment_start': 'Start',
  'segment_end': 'End',
  'segment_name': 'Label name',
  'segment_default_name': 'Label {index}',
  'segment_name_hint': 'Enter label name',
  'segment_time_input_title': 'Enter time',
  'segment_delete_title': 'Delete segment label',
  'segment_delete_confirm': 'Delete "{name}"?',
  'segment_loop': 'Loop segment',
  'volume_warning_title': 'Volume warning',
  'volume_warning_message': 'Volume boost may cause clipping or distortion.',
  'exact_alarm_permission_title': 'Allow exact alarms',
  'exact_alarm_permission_message':
      'To keep auto-resume reliable after long background or screen-off playback, allow exact alarms for this app in system settings.',
  'open_exact_alarm_settings': 'Open exact alarm settings',
  'timer_reliability_checking': 'Checking background timer reliability...',
  'timer_reliability_ready':
      'Background and auto-resume requirements are satisfied.',
  'timer_reliability_missing':
      'Review notification and background permissions to improve timer reliability.',
  'add_playback_queue': 'Create playback queue',
  'default_playback_queue_name': 'Playback queue {number}',
  'edit_playback_queue': 'Edit playback queue',
  'edit_queue_audio': 'Edit queue audio',
  'edit_queue_name': 'Edit queue name',
  'edit_queue_color': 'Edit queue color',
  'remove_queue': 'Remove queue',
  'remove_queue_confirm': 'Remove this playback queue?',
  'queue_added_audio': 'Added to queue',
  'playback_list_audio': 'Audio in playback list',
  'add_audio_to_queue': 'Add audio to queue',
  'add_work_to_queue': 'Add work to queue',
  'empty_playback_queue': 'No audio in queue',
  'queue_add_audio_first': 'Add audio to the queue first',
  'edit': 'Edit',
  'save': 'Save',
  'multi_select': 'Multi-select mode',
  'batch_add_to_playlist': 'Add to playlist',
  'batch_added_to_playlist': 'Added {count} works to the playlist',
  'batch_download': 'Batch download',
  'batch_favorite': 'Batch favorite',
  'batch_unfavorite': 'Batch unfavorite',
  'selected_count': '{count} selected',
};
