const Map<String, String> appLanguageZh = {
  'app_title': 'Doujin Audio',
  'startup_initializing': '正在启动 Doujin Audio…',
  'startup_error_title': 'Doujin Audio 启动失败',
  'startup_error_message': '本地数据不会丢失。你可以重试启动或导出诊断报告。',
  'permission_group_playback': '播放基础',
  'permission_group_reliability': '定时与可靠性',
  'permission_group_advanced': '高级功能',
  'onboarding_title': 'Doujin Audio',
  'onboarding_subtitle': '本地优先的 ASMR 与语音播放器。',
  'onboarding_local': '音频库和播放状态保存在当前设备。',
  'onboarding_online_optional': 'ASMR.ONE 等在线能力始终为可选功能。',
  'onboarding_permissions': '仅在使用对应功能时请求权限。',
  'onboarding_start': '开始使用',
  'privacy_summary_action': '查看隐私摘要',
  'privacy_summary_title': '隐私摘要',
  'privacy_summary_local_title': '默认保存在本地',
  'privacy_summary_local_body': '音频库、设置和播放状态保存在当前设备。',
  'privacy_summary_network_title': '可选在线功能',
  'privacy_summary_network_body': '网络仅用于 ASMR.ONE、元数据和应用更新等功能。',
  'privacy_summary_diagnostics_title': '诊断信息由你控制',
  'privacy_summary_diagnostics_body': '仅在你主动导出时生成脱敏诊断报告。',
  'nav_library': '音频库',
  'open_library': '前往媒体库',
  'open_playback_details': '打开播放详情',
  'retry_playback': '重试播放',
  'nav_sessions': '播放列表',
  'nav_settings': '设置',
  'timer': '计时器',
  'done': '完成',
  'close': '关闭',
  'fullscreen': '全屏',
  'exit_fullscreen': '退出全屏',
  'brightness': '亮度',
  'seek_backward_five_seconds': '后退 5 秒',
  'seek_forward_five_seconds': '前进 5 秒',
  'temporary_double_speed': '临时 2.0 倍速',
  'open_timer_settings': '打开计时器设置',
  'timer_play_plus': '播放 + {time}',
  'asmr_player': 'NL Audio',
  'music_library': '本地音频库',
  'playback_sessions': '播放列表',
  'pin_to_top': '置顶',
  'unpin_from_top': '取消置顶',
  'pinned_to_top': '置顶',
  'settings': '设置',
  'asmr_header_stats': '当前收录{count}个作品',
  'library_header_stats': '{works}个作品  {sessions}首会话',
  'playlist_header_stats': '{sessions}首会话  {playing}首播放中',
  'video_to_audio': '视频转音频',
  'import_audio': '添加音频',
  'import_folder': '添加文件夹',
  'import_file': '添加文件',
  'import_library': '添加曲库',
  'refresh_watched_folder': '刷新监听文件夹',
  'more_actions': '更多操作',
  'sort_by': '排序依据',
  'sort_by_title': '排序依据',
  'sort_description': '说明',
  'sort_name': '名称',
  'sort_voice_actor': '声优',
  'sort_duration': '时长',
  'sort_release_date': '发售时间',
  'sort_added_date': '添加时间',
  'sort_playback_time': '播放时间',
  'sort_ascending': '升序',
  'sort_descending': '降序',
  'sort_group_by_library': '曲库分组',
  'batch_metadata': '批量补全数据',
  'batch_metadata_hint':
      '将从上到下优先获取 ASMR.ONE 作品信息，失败时回退到 DLsite。确认当前作品后，会继续处理下一个作品。',
  'batch_metadata_no_metadata': '缺少全部数据的作品',
  'batch_metadata_any_missing': '有缺少数据的作品',
  'batch_metadata_has_rj_code': '填写了RJ号的作品',
  'batch_metadata_specific': '指定作品',
  'batch_metadata_picker_search': '搜索 RJ 号或标题',
  'batch_metadata_picker_done': '完成 ({count})',
  'batch_metadata_all': '全部数据',
  'batch_metadata_start': '开始补全',
  'batch_metadata_status_searching': '检索中',
  'batch_metadata_status_found': '检索到（未确认）',
  'batch_metadata_status_confirmed': '检索到（已确认）',
  'batch_metadata_status_not_found': '没检索到',
  'batch_metadata_status_failed': '检索失败',
  'batch_metadata_status_excluded': '已排除',
  'batch_metadata_action_exclude': '排除',
  'batch_metadata_action_restore': '恢复',
  'batch_metadata_progress': '{current} / {total}',
  'batch_metadata_load_failed': '无法加载本地曲库，请重试。',
  'batch_metadata_completion_title': '批量补全完成',
  'batch_metadata_completion_saved': '已保存 {count} 条作品数据',
  'batch_metadata_completion_skipped': '已跳过 {count} 条作品数据',
  'batch_metadata_completion_failed': '失败 {count} 条作品数据',
  'library_manage_empty': '还没有添加曲库。',
  'skip': '跳过',
  'search': '搜索',
  'search_audio_placeholder': '搜索音频...',
  'scanning_title': '正在扫描',
  'loading_dot': '正在加载...',
  'playback_loading': '加载中',
  'playback_state_playing': '正在播放',
  'playback_state_paused': '已暂停',
  'playback_failed_retry': '播放失败，点击播放按钮重试',
  'playback_network_failed_retry': '网络连接失败，点击播放按钮重试',
  'asmr_playback_load_failed_retry': '加载失败，点击重试',
  'asmr_playback_network_failed_retry': '网络连接失败，点击重试',
  'asmr_network_failed_retry': '网络连接失败，请下拉重试。',
  'asmr_authentication_failed_retry': '登录状态已失效，请重新登录后重试。',
  'scan_cancel': '取消扫描',
  'scan_cancelled': '扫描已取消。',
  'scan_stage_preparing': '正在读取文件夹...',
  'scan_stage_enumerating': '正在查找音频文件...',
  'scan_stage_merging': '正在读取歌曲信息...',
  'scan_stage_saving': '正在保存音乐库...',
  'scan_stage_covers': '正在加载封面...',
  'scan_processed': '已处理 {processed} 项',
  'scan_processed_total': '已处理 {processed} / {total} 项',
  'scan_current_folder': '当前文件夹',
  'scan_found': '已发现',
  'scan_duplicate': '重复',
  'scan_failure': '失败',
  'audio_count': '{count} 首音频',
  'folder_count': '{count} 个文件夹',
  'no_audio_files': '还没有音频文件',
  'no_audio_found': '未发现音频文件。',
  'no_search_results': '没有匹配的搜索结果',
  'search_try_another_term': '请尝试更换关键词，或清空当前搜索。',
  'search_match_count': '匹配 {match} / 共 {total} 首',
  'import_audio_hint': '点击下方按钮添加音频，支持文件夹或单个文件。',
  'need_storage_permission_scan_folder': '需要存储权限才能扫描文件夹。',
  'need_storage_permission_import_audio': '需要存储权限才能添加音频。',
  'import_audio_failed': '无法添加音频，请重试。',
  'import_failed_next_step': '请确认所选文件或文件夹仍可访问，然后重试。',
  'scan_failed_next_step': '请检查存储权限和来源文件夹是否仍存在，然后重试。',
  'detail_backup_import_failed':
      '有 {count} 项详情备份未能同步，请检查 doujin-audio.json 后重试。',
  'refresh_done_added': '刷新完成：新增 {count} 首音频。',
  'refresh_done_no_new': '未发现新音频。',
  'asmr_refresh_done_updated': '分类内容已更新。',
  'asmr_online_playback': 'ASMR.ONE 在线播放',
  'asmr_online_optional_notice': 'ASMR.ONE 是可选在线功能，仅在使用时连接网络。',
  'asmr_refresh_no_updates': '当前没有新更新。',
  'asmr_refresh_failed': '同步失败，请下拉重试。',
  'asmr_favorite_added': '已加入收藏。',
  'asmr_favorite_removed': '已取消收藏。',
  'asmr_category_sales': '销量',
  'asmr_category_rating': '评分',
  'asmr_category_reviews': '评论数',
  'asmr_category_release': '发售时间',
  'asmr_category_collected': '收录时间',
  'asmr_category_recommendation': '推荐',
  'asmr_category_favorites': '收藏',
  'asmr_category_history': '历史',
  'asmr_account_menu': '账号',
  'asmr_account_title': 'ASMR.ONE 账号',
  'asmr_account_restoring': '正在恢复账号信息…',
  'asmr_login_title': '登录',
  'asmr_login_account': '账号',
  'asmr_login_password': '密码',
  'asmr_login_action': '登录',
  'asmr_logout_action': '退出登录',
  'asmr_logged_in_as': '已登录：{name}',
  'asmr_login_success': '登录成功。',
  'asmr_logout_success': '已退出登录。',
  'asmr_login_failed': '登录失败，请检查账号和密码。',
  'asmr_token_expired': '登录已失效，请重新登录。',
  'asmr_account_sync_now': '立即同步',
  'asmr_account_syncing': '正在同步账号数据...',
  'asmr_account_sync_done': '账号数据已同步。',
  'asmr_account_sync_failed': '账号同步失败，请稍后重试。',
  'asmr_account_not_synced': '尚未同步。',
  'asmr_account_last_sync': '上次同步：{time}',
  'asmr_account_pending_count': '{count} 项变更等待同步',
  'asmr_categories_title': '分类',
  'follow_interface_language': '跟随界面',
  'asmr_page_language': 'ASMR.ONE 语言',
  'asmr_language_zh': '中文',
  'asmr_language_ja': '日文',
  'asmr_language_en': '英文',
  'asmr_search_hint': '搜索作品...',
  'asmr_empty_category': '当前分类暂无内容。',
  'asmr_load_more_hint': '继续上拉加载更多',
  'asmr_add_to_playlist': '添加到播放列表',
  'add_to_playlist': '添加到播放列表',
  'asmr_added_to_playlist': '已添加到播放列表：{title}',
  'asmr_detail_action': '详细信息',
  'asmr_detail_tooltip': '查看作品详细信息',
  'asmr_favorite_action': '收藏',
  'asmr_unfavorite_action': '取消收藏',
  'asmr_add_favorite_tooltip': '加入收藏',
  'asmr_download_action': '下载',
  'asmr_download_work_tooltip': '下载作品',
  'asmr_empty_track_tree': '当前作品没有可展开的音频树。',
  'asmr_circle_label': '社团',
  'asmr_tags_label': '标签',
  'asmr_detail_title': '详细信息',
  'asmr_detail_readonly_hint': '只读模式，不支持编辑或拖拽排序。',
  'asmr_detail_load_failed': '读取作品信息失败，请稍后重试。',
  'asmr_detail_basic_info': '基础信息',
  'asmr_detail_other': '其他信息',
  'asmr_detail_statistics': '统计信息',
  'asmr_detail_release_date': '发售日期',
  'asmr_detail_duration': '时长',
  'asmr_detail_sales': '销量',
  'asmr_detail_rating': '评分',
  'asmr_detail_unrated': '未评分',
  'asmr_detail_reviews': '评论数',
  'asmr_detail_age_rating': '年龄分级',
  'asmr_detail_language_editions': '语言版本',
  'asmr_detail_description': '简介',
  'asmr_unknown_circle': '未知社团',
  'asmr_missing_rj': '未提供 RJ 号',
  'asmr_has_subtitle': '包含字幕',
  'asmr_unknown': '未知',
  'asmr_download_title': '下载',
  'asmr_download_choose_path': '选择路径',
  'asmr_download_change_path': '更改路径',
  'asmr_download_path_missing': '已保存的下载路径不存在，请重新选择路径。',
  'asmr_download_conflict_title': '同名项处理',
  'asmr_download_conflict_message': '目标路径里如果有同名文件或文件夹，要怎么处理？',
  'asmr_download_conflict_skip': '跳过',
  'asmr_download_conflict_overwrite': '覆盖',
  'asmr_download_task_running': '当前已有下载任务在运行',
  'asmr_download_select_required': '请先选择要下载的文件或文件夹',
  'asmr_download_completed_with_failures': '下载完成，但有部分文件失败',
  'asmr_download_failed': '下载失败：{error}',
  'asmr_download_failed_title': '下载失败',
  'asmr_download_failed_next_step': '请检查目标文件夹和网络连接，然后重试。',
  'asmr_download_starting': '下载中',
  'asmr_download_confirm': '确认下载',
  'asmr_download_added_to_list': '已添加至下载列表',
  'asmr_download_task_title': '下载任务',
  'asmr_download_task_not_found': '下载任务不存在',
  'asmr_download_details_title': '下载详情',
  'asmr_download_no_files_selected': '未选择文件',
  'asmr_download_remove_task': '移除下载任务',
  'asmr_download_remove_entry': '移除任务条目',
  'asmr_download_remove_and_delete': '同时删除已下载任务',
  'asmr_download_no_tasks': '暂无下载任务',
  'asmr_download_waiting': '等待中',
  'asmr_download_status': '状态',
  'asmr_download_destination': '目标',
  'asmr_download_progress': '进度',
  'asmr_download_skipped': '已跳过',
  'asmr_download_failed_count': '失败',
  'asmr_download_downloaded': '已下载',
  'asmr_download_total_size': '总大小',
  'asmr_download_task_removed': '已移除任务条目',
  'asmr_download_task_removed_and_deleted': '已移除任务并删除已下载内容',
  'asmr_download_summary_selected': '已选择 {count} 个文件，合计 {size}',
  'asmr_download_empty_folder': '空文件夹',
  'asmr_download_status_preparing': '准备中',
  'asmr_download_status_downloading': '下载中',
  'asmr_download_status_retrying': '正在重试（{attempt}/{max}）',
  'asmr_download_status_paused': '已暂停',
  'asmr_download_status_completed': '已完成',
  'asmr_download_status_failed': '失败',
  'asmr_download_status_idle': '空闲',
  'refresh': '刷新',
  'downloads': '下载列表',
  'choose_music_folder': '选择音乐文件夹',
  'import_done_added': '添加完成：新增 {count} 首音频。',
  'choose_audio_files': '选择音频文件',
  'library_folder_exists': '已有重复文件夹',
  'library_exists': '已有重复曲库',
  'library_file_exists': '已有重复文件',
  'imported_files': '已添加文件',
  'manually_selected_files': '手动选择的文件',
  'file_added': '文件添加',
  'library_category_all': '全部',
  'library_category_tags': '标签',
  'library_category_voice_actors': '声优',
  'library_category_circles': '社团',
  'library_category_no_tags': '暂无标签信息',
  'library_category_no_voice_actors': '暂无声优信息',
  'library_category_no_circles': '暂无社团信息',
  'library_category_no_matches': '没有匹配的音频',
  'copied_to_clipboard': '已复制：{value}',
  'remove_folder': '移除文件夹',
  'remove_folder_confirm': '要从音乐库移除该文件夹及其所有音频吗？\n\n{name}',
  'cancel': '取消',
  'remove': '移除',
  'removed_prefix': '已移除：{name}',
  'session_created': '已创建会话：{name}',
  'items_count': '{count} 项',
  'play_first': '播放第一首',
  'remove_audio_folder': '移除文件夹',
  'play': '播放',
  'create_another_session': '再创建一个会话',
  'remove_audio': '移除音频',
  'audio_detail': '详细信息',
  'audio_detail_title': '详细信息',
  'audio_detail_library_root': '音频库根文件夹',
  'audio_detail_single_file': '单独添加的音频',
  'audio_detail_cover_image': '封面图片',
  'audio_detail_folder_name': '文件夹名称',
  'audio_detail_file_name': '文件名称',
  'audio_detail_rj_code': 'RJ号',
  'audio_detail_work_title': '作品标题',
  'audio_detail_circle_name': '社团',
  'audio_detail_voice_actors': '声优',
  'audio_detail_tags': '标签',
  'audio_detail_release_date': '发售日期',
  'audio_detail_sales_count': '销量',
  'audio_detail_rating': '评分',
  'audio_detail_empty': '未填写',
  'audio_detail_edit_title': '编辑{name}',
  'audio_detail_multi_hint': '多个词条请使用中文逗号“，”分隔',
  'audio_detail_backup_failed': '已保存到数据库，但本地备份失败。',
  'audio_detail_cover_portability_skipped': '封面超过 8 MiB，仅保留本机路径，未写入便携备份。',
  'audio_detail_restored_from_backup': '已从本地备份恢复。',
  'audio_detail_rj_format_hint': 'RJ号格式建议为 RJ + 数字。',
  'audio_detail_save_failed': '保存失败，请重试。',
  'audio_detail_load_failed': '读取失败，请重试。',
  'audio_detail_duration_calculation_failed': '无法计算时长，请重试。',
  'audio_detail_fetch_info': '获取信息',
  'audio_detail_fetch_scope_title': '选择获取范围',
  'audio_detail_fetch_scope_hint':
      '将优先通过 ASMR.ONE 获取作品信息，失败时回退到 DLsite。请选择要写入的范围。',
  'audio_detail_fetch_scope_all_hint': '使用获取到的信息覆盖当前详细信息。',
  'audio_detail_fetch_scope_missing_hint': '只填写当前为空的详细信息，已有内容保持不变。',
  'metadata_scope_missing': '缺少数据',
  'audio_detail_fetch_missing_query': '请先填写RJ号、文件夹/文件名称或作品标题。',
  'audio_detail_cover_swipe_hint': '左右滑动切换',
  'audio_detail_set_cover': '作为封面',
  'audio_detail_current_cover': '当前封面',
  'audio_detail_rename_file': '重命名文件',
  'audio_detail_rename_failed': '重命名失败，请检查文件是否存在或正在被占用。',
  'dlsite_review_title': '确认作品数据',
  'dlsite_save_cover': '保存封面到文件夹',
  'dlsite_fetch_failed': '获取作品数据失败，请检查RJ号、文件夹/文件名称、作品标题或网络后重试。',
  'dlsite_cover_save_failed': '信息已保存，但封面保存失败。',
  'confirm': '确认',
  'retry': '重试',
  'undo': '撤销',
  'items_removed_count': '已移除 {count} 项',
  'removal_failed': '部分删除或移除操作失败，请重试',
  'previous': '上一项',
  'next': '下一项',
  'clear_all_sessions': '清空全部会话',
  'stop_remove_all_sessions': '停止并移除所有正在运行的播放会话？',
  'clear': '清空',
  'all_sessions_cleared': '已清空全部会话。',
  'audio_removed': '已移除音频。',
  'audio_excluded': '已从曲库中排除音频。',
  'folder_audio_removed': '已移除文件夹下该音频',
  'folder_removed': '已移除文件夹',
  'folder_excluded': '已从曲库中排除文件夹。',
  'pause_all_sessions': '暂停全部会话',
  'all_paused': '已暂停全部会话。',
  'no_active_sessions': '当前没有活跃会话',
  'go_library_hint': '请先到音乐库播放音频，再创建并发会话。',
  'single_loop': '单曲循环',
  'pause_after_playback': '一轮循环后暂停',
  'loop_mode_title': '循环方式',
  'sequential_playback': '顺序播放',
  'loop_playback': '顺序播放',
  'shuffle_playback': '随机播放',
  'cross_folder': '跨文件夹',
  'current_folder': '当前文件夹',
  'random_order': '随机',
  'sequential_order': '顺序',
  'no_other_audio_in_folder': '该文件夹没有可切换的其他音频。',
  'switch_audio': '切换音频',
  'channel_swap': '左右声道调换',
  'channel_swap_desc': '交换左右声道输出。',
  'skip_silence': '跳过空白',
  'skip_silence_desc': '缩短无声片段。',
  'noise_reduction': '轻度降噪',
  'noise_reduction_desc': '削弱尖锐底噪。',
  'volume_normalization': '音量平衡',
  'volume_normalization_desc': '限制突发音量并均衡整体音量。',
  'audio_features': '功能',
  'equalizer': '均衡器',
  'time_segments': '时间段',
  'equalizer_supported': '按当前设备频段调节',
  'equalizer_enable_hint': '开启后将读取设备支持的频段',
  'equalizer_unavailable': '当前设备暂未返回 EQ 频段；可先开启均衡器后稍等刷新。',
  'eq_preset': '预设',
  'eq_reset': '重置',
  'eq_save_preset': '保存预设',
  'eq_delete_preset': '删除预设',
  'eq_preset_name': '预设名称',
  'mute': '静音',
  'unmute': '取消静音',
  'eq_preset_flat': '平直',
  'eq_preset_asmr_immersive': 'ASMR 沉浸',
  'eq_preset_voice_clear': '人声清晰',
  'eq_preset_ear_massage': '耳部按摩',
  'eq_preset_night_soft': '夜间柔和',
  'eq_preset_bass_boost': '低音增强',
  'previous_track': '上一首',
  'pause': '暂停',
  'resume': '恢复',
  'next_track': '下一首',
  'collapse': '收起',
  'expand': '展开',
  'end_session': '结束会话',
  'random_play': '随机播放',
  'sequential_play': '顺序播放',
  'cross_folder_play': '跨文件夹播放',
  'current_folder_only': '仅当前文件夹',
  'dark_mode': '外观模式',
  'cover_image_resolution': '封面清晰度',
  'cover_image_resolution_300': '300px',
  'cover_image_resolution_600': '600px',
  'cover_image_resolution_900': '900px',
  'cover_image_resolution_1200': '1200px',
  'cover_image_resolution_original': '原画',
  'cover_image_display_mode': '封面图片显示',
  'cover_image_display_mode_fill': '填充',
  'cover_image_display_mode_stretch': '拉伸',
  'cover_image_display_mode_tile': '平铺',
  'prefer_embedded_audio_cover': '音频优先显示自身封面',
  'theme_system': '跟随系统',
  'theme_light': '浅色',
  'theme_dark': '深色',
  'black_theme': '纯黑主题',
  'differentiate_asmr_theme': 'ASMR.ONE 独立配色',
  'app_theme_color': '应用主题颜色',
  'asmr_theme_color': 'ASMR.ONE 主题颜色',
  'theme_color_coral': '珊瑚色',
  'theme_color_rose': '玫红色',
  'theme_color_pink': '粉紫色',
  'theme_color_lavender': '淡紫色',
  'theme_color_periwinkle': '长春花蓝',
  'theme_color_blue': '蓝色',
  'theme_color_sky': '天蓝色',
  'theme_color_cyan': '青色',
  'theme_color_mint': '薄荷色',
  'theme_color_green': '绿色',
  'theme_color_light_green': '浅绿色',
  'theme_color_lime': '黄绿色',
  'theme_color_amber': '琥珀色',
  'theme_color_orange': '橙色',
  'theme_color_peach': '蜜桃色',
  'theme_color_gray': '灰色',
  'playback_detail_subtitle_style': '字幕样式',
  'playback_detail_subtitle_style_compact': '简洁字幕',
  'playback_detail_subtitle_style_timeline': '时间轴字幕',
  'seek_to_subtitle': '跳转到此字幕',
  'blur_player_background': '播放页模糊背景',
  'ui_blur_effect': '界面毛玻璃',
  'multi_thread_playback': '多线程播放',
  'allow_video_playback': '允许播放视频',
  'notification_bar': '播放通知控制',
  'show_playback_card': '显示播放卡片',
  'section_detail_info': '详细信息',
  'card_info_display': '卡片显示内容',
  'card_info_display_subtitle': '已选择 {count} / {max} 项',
  'card_info_none': '不显示',
  'card_info_release_date': '发售',
  'card_info_sales_count': '销量',
  'card_info_rating': '评分',
  'card_info_duration': '时长',
  'auto_play_added_sessions': '添加至列表后立刻播放',
  'audio_device_disconnect_behavior': '耳机/蓝牙断开时',
  'audio_device_disconnect_pause': '暂停',
  'audio_device_disconnect_continuePlayback': '继续',
  'audio_focus_strategy': '音频焦点策略',
  'audio_focus_strategy_standard': '标准',
  'audio_focus_strategy_mixWithOthers': '重叠',
  'transient_audio_focus_loss_behavior': '其他声音打断时',
  'transient_audio_focus_loss_duck': '降低音量',
  'transient_audio_focus_loss_pause': '暂停',
  'interruption_resume_behavior': '通话结束后',
  'interruption_resume_stayPaused': '保持暂停',
  'interruption_resume_resume': '自动恢复',
  'asmr_playback_cache': '缓存 ASMR.ONE 音频',
  'record_playback_progress': '记忆播放进度',
  'section_language': '语言',
  'section_language_subtitle': '界面与内容语言',
  'section_common': '通用',
  'section_common_subtitle': '启动、行为与系统选项',
  'settings_group_startup_behavior': '启动设置',
  'settings_group_general_behavior': '通用行为',
  'settings_group_page_display': '页面显示',
  'show_local_library': '本地音频库',
  'show_asmr_one': 'ASMR.ONE',
  'settings_group_theme_layout': '主题与布局',
  'settings_group_cover_background': '封面与背景',
  'settings_group_playback_detail': '播放详情',
  'settings_group_playback_behavior': '播放行为',
  'settings_group_audio_recovery': '音频与恢复',
  'settings_group_download': '下载',
  'settings_group_download_files': '文件与命名',
  'settings_group_data': '数据与支持',
  'settings_group_cache': '缓存',
  'settings_group_permissions': '权限与后台',
  'settings_group_updates': '更新',
  'section_appearance': '外观',
  'section_appearance_subtitle': '主题、布局与字幕外观',
  'section_playback': '播放',
  'section_playback_subtitle': '播放控制、音频与恢复',
  'section_asmr_download': 'ASMR.ONE 下载',
  'section_asmr_download_subtitle': '下载设置与文件命名',
  'asmr_download_path_setting': '下载位置',
  'asmr_download_path_not_set': '未设置',
  'asmr_download_conflict_setting': '同名文件处理',
  'asmr_download_retry_count': '自动重试次数',
  'asmr_download_thread_count': '线程数',
  'asmr_download_save_metadata_setting': '保存数据信息',
  'asmr_download_save_cover': '保存封面图片',
  'asmr_download_folder_name_setting': '文件夹名称',
  'asmr_download_folder_name_hint': '勾选要使用的字段，并拖动已选字段调整顺序；至少保留一项。',
  'asmr_download_folder_field_rj_code': 'RJ号',
  'asmr_download_folder_field_voice_actors': '声优名',
  'asmr_download_folder_field_circle_name': '社团',
  'asmr_download_folder_field_work_title': '作品名称',
  'section_data_storage': '数据与存储',
  'section_data_storage_subtitle': '缓存与数据管理',
  'section_updates_permissions': '更新与权限',
  'section_updates_permissions_subtitle': '权限、更新与后台运行',
  'permission_enabled': '已开启',
  'permission_not_enabled': '未开启',
  'permission_state_authorized': '已授权',
  'permission_state_unauthorized': '未授权',
  'permission_state_restricted': '受限',
  'permission_state_recommended': '建议开启',
  'system_settings_open_failed': '无法打开系统设置，请从系统应用设置中手动调整。',
  'permission_notification_description': '用于显示后台播放状态和媒体控制。',
  'permission_background_description': '减少部分设备在息屏后限制后台播放的概率。',
  'permission_manage_files_description': '仅用于需要直接遍历文件系统的高级曲库扫描；推荐优先使用系统文件夹选择器。',
  'permission_overlay_description': '仅用于在其他应用上方显示全局字幕。',
  'permission_update_install_description': '仅用于安装用户主动下载的 GitHub Release 更新。',
  'storage_usage_title': '存储空间',
  'storage_usage_total': '手机总空间',
  'storage_usage_audio_library': '本地音频库',
  'storage_usage_app_cache': '应用缓存',
  'storage_usage_other': '其他占用',
  'storage_usage_available': '剩余空间',
  'storage_usage_unavailable': '暂时无法读取存储空间。',
  'storage_usage_retry': '重新读取存储空间',
  'operation_completed': '已完成',
  'operation_failed': '操作失败',
  'export_diagnostics': '导出诊断报告',
  'export_backup': '导出备份',
  'export_backup_subtitle': '备份应用数据、播放记录以及 ASMR.ONE 登录账号。',
  'restore_backup': '恢复备份',
  'restore_backup_subtitle': '完整替换当前数据，并在下次启动时生效。',
  'backup_sensitive_warning':
      '备份包含 ASMR.ONE 账号、密码和登录令牌，且文件不加密。任何获得备份文件的人都可能直接登录该账号。是否继续？',
  'restore_backup_warning': '恢复会完整替换当前应用数据并停止播放。音频文件和目录授权不会恢复，完成后必须关闭并重新启动应用。',
  'select_backup': '选择备份',
  'backup_exported': '备份已导出至：{path}',
  'backup_ready_to_restore': '备份已准备完成',
  'backup_restart_required': '备份已通过校验，将在下次启动时恢复。请立即关闭并重新启动应用。',
  'backup_restore_succeeded': '备份恢复成功，应用数据和 ASMR.ONE 账号已更新。',
  'backup_restore_failed_rolled_back': '备份恢复失败，已安全恢复为原有数据。',
  'unexpected_error_title': 'Doujin Audio 遇到意外错误',
  'unexpected_error_message': '本地数据不会丢失。你可以导出诊断报告，然后关闭并重新启动应用。',
  'close_and_restart': '关闭并重新启动',
  'export_diagnostics_subtitle': '导出脱敏日志等诊断信息。',
  'diagnostics_exported': '诊断报告已导出至：{path}',
  'operation_failed_retry': '操作失败，请重试。',
  'operation_failed_diagnostics_hint': '请重试；如果持续失败，可以导出诊断报告协助排查。',
  'section_danger_zone': '其他',
  'allow_background_run': '允许后台运行',
  'allow_background_run_subtitle': '防止息屏后后台播放被限制。',
  'allow_background_run_ready': '系统已允许本应用后台运行，息屏播放会更稳定。',
  'allow_background_run_checking': '正在检查后台运行状态...',
  'allow_background_run_open_failed': '无法打开系统后台运行设置，请手动进入应用设置调整。',
  'notification_permission_status': '通知权限状态',
  'notification_permission_ready': '通知权限已开启，后台控制可正常显示，息屏播放更稳定。',
  'notification_permission_missing': '通知权限未开启，系统可能限制后台播放通知与控制显示。',
  'notification_permission_checking': '正在检查通知权限...',
  'notification_settings_open_failed': '无法打开通知设置，请手动进入系统设置调整。',
  'open_notification_settings': '打开通知设置',
  'exact_alarm_permission_ready': '精确定时已可用，长时间后台定时恢复会更稳定。',
  'exact_alarm_permission_missing': '精确定时未开启，长时间后台后的自动恢复可能不可靠。',
  'clear_app_cache': '清理应用缓存',
  'clear_app_cache_confirm': '将清理当前应用产生的缓存文件，不会删除音乐库源文件。是否继续？',
  'app_cache_cleaned': '已清理 {size} 缓存。',
  'app_cache_none': '没有可清理的应用缓存。',
  'max_cache_size': '临时缓存上限',
  'check': '检查',
  'check_updates': '检查更新',
  'auto_check_updates': '自动检查更新',
  'check_updates_subtitle_latest': '当前已是最新版本：{version}',
  'checking_updates': '正在检查 GitHub 最新版本...',
  'latest_version_available': '发现新版本',
  'open_release_page': '打开发布页面',
  'current_version_label': '当前版本：{version}',
  'latest_version_label': '最新版本：{version}',
  'update_available_subtitle': '发现可更新版本：{version}',
  'download_update': '下载更新',
  'downloading_update': '正在下载更新：{percent}%',
  'no_updates_available': '当前已是最新版本。',
  'update_no_compatible_release': '当前暂无兼容的稳定版本。',
  'update_missing_asset': '最新版本缺少当前平台的安装包。',
  'update_missing_checksum': '最新版本缺少 SHA-256 校验文件。',
  'update_check_failed': '检查更新失败，请稍后重试。',
  'update_check_failed_next_step': '请检查网络连接或 GitHub 访问状态，然后重试。',
  'update_download_failed': '下载更新失败，请检查网络后重试。',
  'update_download_failed_next_step':
      '更新下载或 SHA-256 校验未完成。你可以重试，或打开 GitHub Release 页面手动下载。',
  'update_install_preparing_title': '正在准备安装',
  'update_install_preparing_message':
      '版本 {version} 已下载并通过 SHA-256 校验。应用可能会自动关闭并重启以完成更新。文件：{path}',
  'update_ready_install': '安装器已打开，请按提示完成更新。',
  'update_install_failed': '无法继续安装更新',
  'update_install_failed_next_step':
      '请稍后重试；如果仍失败，请查看更新日志，或打开 GitHub Release 页面手动安装。',
  'update_install_failed_with_detail': '请稍后重试；如果仍失败，请查看更新日志。详情：{detail}',
  'open_update_log': '查看日志',
  'install_permission_needed': '请先允许本应用安装未知来源应用。',
  'install_permission_title': '允许安装更新',
  'install_permission_message': '为了继续下载并安装新版本，需要先允许本应用安装未知来源应用。现在前往系统设置开启吗？',
  'transcode_defaults': '转码默认参数',
  'format': '格式',
  'bitrate': '码率',
  'bitrate_used': 'MP3 / AAC / OGG 输出会使用该码率。',
  'bitrate_not_used': '{format} 使用格式内置编码参数，码率设置不生效。',
  'about': '关于',
  'about_subtitle': '版本、作者与项目信息',
  'app_desc': '支持并发会话与高保真音频播放。',
  'about_version': '版本',
  'about_source_code': '源代码',
  'about_wiki': 'wiki',
  'about_wiki_open_failed': '无法打开 GitHub 项目页面。',
  'about_author': '作者',
  'about_reward': '打赏',
  'about_reward_open_failed': '无法打开爱发电打赏页面。',
  'language': '语言',
  'interface_language': '界面语言',
  'follow_system': '跟随系统',
  'startup_page': '启动页',
  'portrait_lock': '竖屏锁定',
  'startup_page_asmrOne': 'ASMR.ONE',
  'startup_page_library': '本地音频库',
  'startup_page_playlist': '播放列表',
  'allow_duplicate_works': '允许添加相同作品',
  'reduce_animations': '减少动画',
  'haptic_feedback_enabled': '操作震动',
  'dlsite_metadata_language': 'DLsite 信息语言',
  'timer_title': '计时器',
  'set_countdown': '设置倒计时',
  'sleep_mode': '睡眠模式',
  'sleep_mode_auto_trigger': '睡眠模式',
  'sleep_mode_auto_trigger_subtitle': '进入纯黑锁屏睡眠模式的触发条件',
  'sleep_mode_auto_trigger_manual': '手动开启',
  'sleep_mode_auto_trigger_afterPlayback5min': '音频播放后5min',
  'sleep_mode_auto_trigger_afterCountdown5min': '倒计时开启后5min',
  'sleep_canvas': '纯黑睡眠模式',
  'stop_after_current_track': '当前音轨播完后停止',
  'stop_after_current_track_subtitle': '播放完当前曲目后自动暂停停止',
  'hold_to_exit_sleep_mode': '长按退出',
  'no_timer_set': '未设置倒计时',
  'sleep_countdown': '睡眠倒计时',
  'double_tap_to_play_pause': '双击播放 / 暂停',
  'swipe_to_adjust_track_volume': '上下滑动调节音量',
  'start_mode': '启动方式',
  'confirm_start_now': '确认并立即开始',
  'confirm_wait_playback': '确认并等待播放触发',
  'set_duration_first': '请先设置倒计时时长。',
  'cancel_timer': '取消计时',
  'auto_resume_after_timer': '定时恢复播放',
  'auto_resume_subtitle': '设定时间自动恢复播放。',
  'resume_time': '恢复时间：{time}',
  'tap_choose_resume_time': '点击选择自动恢复播放的时刻',
  'choose_auto_resume_time': '选择自动恢复时间',
  'set_timer_to_enable_auto_resume': '设置倒计时后，可在此开启自动恢复播放功能。',
  'wait_play_trigger': '等待播放触发',
  'manual_start': '立刻开始计时',
  'auto_start_after_play': '音频播放后计时',
  'countdown_finished': '倒计时已结束',
  'waiting_to_start_countdown': '等待播放后开始计时',
  'counting_down': '倒计时进行中',
  'waiting_for_auto_resume': '等待定时恢复播放',
  'paused_audio_count': '已暂停 {count} 个音频',
  'auto_resume_at': '将在 {time} 自动恢复',
  'hour': '小时',
  'minute': '分钟',
  'second': '秒',
  'manual_start_subtitle': '立即启动倒计时。',
  'trigger_start_subtitle': '检测到播放时启动倒计时。',
  'selected_file': '已选择：{name}',
  'select_video_and_output': '请先选择视频文件和输出目录。',
  'conversion_starting': '开始转换...',
  'converting_percent': '转换中：{percent}%',
  'conversion_done_saved': '转换完成，已保存至：{path}',
  'video_conversion_completed': '视频转音频完成',
  'video_conversion_failed_title': '视频转音频失败',
  'conversion_canceled': '转换已取消。',
  'conversion_failed': '转换失败，请重试。',
  'canceling_conversion': '正在取消转换...',
  'source_video_file': '视频源文件',
  'tap_select_video_file': '点击选择需要转换的视频文件',
  'output_directory': '输出目录',
  'tap_select_output_dir': '点击选择音频保存位置',
  'current_params': '当前参数：{value}',
  'format_auto_encode': '格式自动编码',
  'cancel_conversion': '取消转换',
  'notification_permission_title': '开启通知权限',
  'notification_permission_message':
      '当前系统没有允许本应用显示通知，所以播放通知栏不会出现。请打开应用通知权限和媒体通知开关。',
  'notification_permission_enabled': '通知权限已开启。',
  'background_play_permission_title': '允许后台播放',
  'background_play_permission_message': '为了在息屏后继续播放音频，需要将本应用设为不限制电量。前往系统设置开启吗？',
  'manage_files_permission_title': '允许管理所有文件',
  'manage_files_permission_message':
      '当前应用还没有开启“管理所有文件”权限，添加文件夹、曲库和读取本地资源可能会失败。现在前往系统设置开启吗？',
  'manage_files_permission_enabled': '管理所有文件权限已开启。',
  'go_settings': '去设置',
  'later': '稍后',
  'start_conversion': '开始转换',
  'choose_library': '添加曲库',
  'choose_library_folder': '选择曲库文件夹',
  'import_library_done': '曲库添加完成：新增 {folderCount} 个根文件夹，{count} 首音频。',
  'no_child_folder_found': '所选文件夹下没有可添加的下一层文件夹。',
  'edit_library': '编辑曲库',
  'edit_library_hint': '管理已添加的曲库、文件夹和音频',
  'library_removed': '曲库已移除。',
  'remove_library': '移除曲库',
  'remove_library_confirm': '要移除该曲库及其已添加的所有文件夹吗？\n\n{name}',
  'excluded': '已排除',
  'restore': '恢复',
  'exclude': '排除',
  'library_edit_empty': '还没有添加曲库。',
  'subtitle_window_settings': '字幕悬浮窗',
  'subtitle_window_preview': '实时预览',
  'subtitle_preview_sample': '海浪声正在慢慢靠近，呼吸也跟着放松下来。',
  'font_setting': '字体设置',
  'system_default': '系统默认',
  'font_color': '文字颜色',
  'background_opacity': '背景透明度',
  'background_transparency': '背景透明度',
  'background_color': '背景颜色',
  'reset_to_default': '重置为默认',
  'restore_default': '恢复默认',
  'turn_on_subtitle': '打开字幕',
  'turn_off_subtitle': '关闭字幕',
  'subtitle_global_display': '字幕全局显示',
  'overlay_permission_title': '允许悬浮窗显示字幕',
  'overlay_permission_message':
      '开启字幕全局显示前，需要先允许本应用显示悬浮窗，这样切到后台或其他页面时字幕才能继续显示。现在前往系统设置开启吗？',
  'border_depth': '边框深度',
  'font_size': '字号',
  'volume': '音量',
  'volume_range_hint': '0-150',
  'playback_speed': '播放速度',
  'volume_balance': '声道平衡',
  'speed_reset': '恢复 1.0x',
  'segment_add': '添加时间段标签',
  'segment_start': '起点',
  'segment_end': '终点',
  'segment_name': '标签名称',
  'segment_default_name': '标签{index}',
  'segment_name_hint': '输入标签名称',
  'segment_time_input_title': '输入时间',
  'segment_delete_title': '删除标签',
  'segment_delete_confirm': '要删除标签“{name}”吗？',
  'segment_loop': '循环播放',
  'volume_warning_title': '音量警告',
  'volume_warning_message': '增强音量可能导致削波或失真',
  'exact_alarm_permission_title': '允许精确定时',
  'exact_alarm_permission_message':
      '为了让熄屏、后台和长时间后的自动恢复播放更稳定，建议在系统中允许本应用使用精确定时。',
  'open_exact_alarm_settings': '打开精确定时设置',
  'timer_reliability_checking': '正在检查定时器后台可靠性...',
  'timer_reliability_ready': '后台与自动恢复条件已满足',
  'timer_reliability_missing': '建议补全后台与定时权限以提升稳定性',
  'add_playback_queue': '创建播放队列',
  'default_playback_queue_name': '播放队列 {number}',
  'edit_playback_queue': '编辑播放队列',
  'edit_queue_audio': '编辑队列音频',
  'edit_queue_name': '编辑队列名称',
  'edit_queue_color': '编辑队列颜色',
  'remove_queue': '移除队列',
  'remove_queue_confirm': '要移除此播放队列及其队列配置吗？',
  'queue_added_audio': '已添加至队列',
  'playback_list_audio': '播放列表中的音频',
  'add_audio_to_queue': '添加该音频至队列',
  'add_work_to_queue': '添加该音频所在作品至队列',
  'empty_playback_queue': '队列中暂无音频',
  'queue_add_audio_first': '请先向队列添加音频',
  'edit': '编辑',
  'save': '保存',
  'multi_select': '多选模式',
  'batch_add_to_playlist': '添加至播放列表',
  'batch_added_to_playlist': '已添加 {count} 个作品至播放列表',
  'batch_download': '批量下载',
  'batch_favorite': '批量收藏',
  'batch_unfavorite': '批量取消收藏',
  'selected_count': '已选择 {count} 项',
};
